// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveFixedExpense(arg1) {
  return window['go']['desktop']['App']['ArchiveFixedExpense'](arg1);
}

export function Bootstrap() {
  return window['go']['desktop']['App']['Bootstrap']();
}

export function CompleteOnboarding(arg1) {
  return window['go']['desktop']['App']['CompleteOnboarding'](arg1);
}

export function ConfirmFixedExpenseOccurrence(arg1, arg2) {
  return window['go']['desktop']['App']['ConfirmFixedExpenseOccurrence'](arg1, arg2);
}

export function CreateAccount(arg1) {
  return window['go']['desktop']['App']['CreateAccount'](arg1);
}

export function CreateFixedExpense(arg1) {
  return window['go']['desktop']['App']['CreateFixedExpense'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['desktop']['App']['CreateTransaction'](arg1);
}

export function CheckForUpdates() {
  return window['go']['desktop']['App']['CheckForUpdates']();
}

export function DeleteAccount(arg1) {
  return window['go']['desktop']['App']['DeleteAccount'](arg1);
}

export function DismissFixedExpenseOccurrence(arg1) {
  return window['go']['desktop']['App']['DismissFixedExpenseOccurrence'](arg1);
}

export function FixedExpensesOverview() {
  return window['go']['desktop']['App']['FixedExpensesOverview']();
}

export function GetUpdateStatus() {
  return window['go']['desktop']['App']['GetUpdateStatus']();
}

export function ImportBankStatement(arg1) {
  return window['go']['desktop']['App']['ImportBankStatement'](arg1);
}

export function InstallUpdate() {
  return window['go']['desktop']['App']['InstallUpdate']();
}

export function ListTransactions() {
  return window['go']['desktop']['App']['ListTransactions']();
}

export function CreditCardsOverview() {
  return window['go']['desktop']['App']['CreditCardsOverview']();
}

export function PayCreditCardInvoice(arg1, arg2) {
  return window['go']['desktop']['App']['PayCreditCardInvoice'](arg1, arg2);
}

export function ReopenFixedExpenseOccurrence(arg1) {
  return window['go']['desktop']['App']['ReopenFixedExpenseOccurrence'](arg1);
}

export function RestoreFixedExpense(arg1) {
  return window['go']['desktop']['App']['RestoreFixedExpense'](arg1);
}

export function RestoreTransaction(arg1) {
  return window['go']['desktop']['App']['RestoreTransaction'](arg1);
}

export function SetBalancesHidden(arg1) {
  return window['go']['desktop']['App']['SetBalancesHidden'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['desktop']['App']['SetTheme'](arg1);
}

export function SkipOnboarding() {
  return window['go']['desktop']['App']['SkipOnboarding']();
}

export function TrashTransaction(arg1) {
  return window['go']['desktop']['App']['TrashTransaction'](arg1);
}

export function UpdateAccount(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateAccount'](arg1, arg2);
}

export function UpdateFixedExpense(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateFixedExpense'](arg1, arg2);
}

export function UpdateTransaction(arg1, arg2) {
  return window['go']['desktop']['App']['UpdateTransaction'](arg1, arg2);
}
