// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {application} from '../models';
import {domain} from '../models';

export function ArchiveFixedExpense(arg1:string):Promise<void>;

export function Bootstrap():Promise<application.Bootstrap>;

export function CompleteOnboarding(arg1:application.OnboardingInput):Promise<domain.Profile>;

export function ConfirmFixedExpenseOccurrence(arg1:string,arg2:application.ConfirmFixedExpenseOccurrenceInput):Promise<domain.Transaction>;

export function CreateAccount(arg1:application.AccountInput):Promise<domain.Account>;

export function CreateFixedExpense(arg1:application.FixedExpenseInput):Promise<domain.FixedExpense>;

export function CreateTransaction(arg1:application.TransactionInput):Promise<domain.Transaction>;

export function CheckForUpdates():Promise<any>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DismissFixedExpenseOccurrence(arg1:string):Promise<void>;

export function FixedExpensesOverview():Promise<application.FixedExpensesOverview>;

export function GetUpdateStatus():Promise<any>;

export function ImportBankStatement(arg1:application.BankStatementInput):Promise<application.BankStatementImportResult>;

export function InstallUpdate():Promise<any>;

export function ListTransactions():Promise<Array<domain.Transaction>>;

export function CreditCardsOverview():Promise<application.CreditCardsOverview>;

export function PayCreditCardInvoice(arg1:string,arg2:application.CreditCardPaymentInput):Promise<domain.CreditCardPayment>;

export function ReopenFixedExpenseOccurrence(arg1:string):Promise<void>;

export function RestoreFixedExpense(arg1:string):Promise<void>;

export function RestoreTransaction(arg1:string):Promise<void>;

export function SetBalancesHidden(arg1:boolean):Promise<domain.Profile>;

export function SetTheme(arg1:domain.Theme):Promise<domain.Profile>;

export function SkipOnboarding():Promise<domain.Profile>;

export function TrashTransaction(arg1:string):Promise<void>;

export function UpdateAccount(arg1:string,arg2:application.AccountInput):Promise<domain.Account>;

export function UpdateFixedExpense(arg1:string,arg2:application.FixedExpenseInput):Promise<domain.FixedExpense>;

export function UpdateTransaction(arg1:string,arg2:application.TransactionInput):Promise<domain.Transaction>;
