// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {application} from '../models';
import {updater} from '../models';
import {desktop} from '../models';
import {domain} from '../models';

export function ArchiveFixedExpense(arg1:string):Promise<void>;

export function AdjustAccountBalance(arg1:string,arg2:application.BalanceAdjustmentInput):Promise<domain.Transaction>;

export function BackupStatus():Promise<storage.BackupStatus>;

export function Bootstrap():Promise<application.Bootstrap>;

export function ChangeEncryptionPassword(arg1:application.ChangeEncryptionPasswordInput):Promise<void>;

export function CheckForUpdates():Promise<updater.Status>;

export function ChooseBackupFolder():Promise<desktop.OperationResult>;

export function CompleteOnboarding(arg1:application.OnboardingInput):Promise<domain.Profile>;

export function ConfirmFixedExpenseOccurrence(arg1:string,arg2:application.ConfirmFixedExpenseOccurrenceInput):Promise<domain.Transaction>;

export function CreateAccount(arg1:application.AccountInput):Promise<domain.Account>;

export function CreateBackup():Promise<desktop.BackupDialogResult>;

export function CreateFixedExpense(arg1:application.FixedExpenseInput):Promise<domain.FixedExpense>;

export function CreateTransaction(arg1:application.TransactionInput):Promise<domain.Transaction>;

export function CreditCardsOverview():Promise<application.CreditCardsOverview>;

export function DeleteAccount(arg1:string):Promise<void>;

export function DeleteTransactionPermanently(arg1:string):Promise<void>;

export function DisableEncryption(arg1:application.UnlockInput):Promise<storage.SecurityStatus>;

export function DismissFixedExpenseOccurrence(arg1:string):Promise<void>;

export function EmptyTransactionTrash():Promise<void>;

export function EnableEncryption(arg1:application.EncryptionInput):Promise<storage.EncryptionResult>;

export function ExportData(arg1:string):Promise<desktop.OperationResult>;

export function FixedExpensesOverview():Promise<application.FixedExpensesOverview>;

export function GetUpdateStatus():Promise<updater.Status>;

export function ImportBankStatement(arg1:application.BankStatementInput):Promise<application.BankStatementImportResult>;

export function InspectBackup():Promise<desktop.BackupDialogResult>;

export function InstallUpdate():Promise<updater.Status>;

export function ListTransactions():Promise<Array<domain.Transaction>>;

export function ListTrashedTransactions():Promise<Array<domain.Transaction>>;

export function PayCreditCardInvoice(arg1:string,arg2:application.CreditCardPaymentInput):Promise<domain.CreditCardPayment>;

export function RecoverEncryption(arg1:application.RecoverEncryptionInput):Promise<storage.SecurityStatus>;

export function ReopenFixedExpenseOccurrence(arg1:string):Promise<void>;

export function ResetBackupFolder():Promise<storage.BackupStatus>;

export function RestoreBackup(arg1:application.RestoreBackupInput):Promise<desktop.BackupDialogResult>;

export function RestoreFixedExpense(arg1:string):Promise<void>;

export function RestoreTransaction(arg1:string):Promise<void>;

export function SecurityStatus():Promise<storage.SecurityStatus>;

export function SetBalancesHidden(arg1:boolean):Promise<domain.Profile>;

export function SetTheme(arg1:domain.Theme):Promise<domain.Profile>;

export function SetVersion(arg1:string):Promise<void>;

export function SkipOnboarding():Promise<domain.Profile>;

export function TrashTransaction(arg1:string):Promise<void>;

export function UnlockDatabase(arg1:application.UnlockInput):Promise<storage.SecurityStatus>;

export function UpdateAccount(arg1:string,arg2:application.AccountInput):Promise<domain.Account>;

export function UpdateFixedExpense(arg1:string,arg2:application.FixedExpenseInput):Promise<domain.FixedExpense>;

export function UpdateTransaction(arg1:string,arg2:application.TransactionInput):Promise<domain.Transaction>;
