import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { expect, test, vi } from 'vitest'
import App from './App'
import { SearchCombobox } from './components'
import type { BootstrapData, Profile, Transaction } from './types'

const profile: Profile={displayName:'Ana',currency:'BRL',theme:'light',onboardingStatus:'completed'}
const empty:BootstrapData={profile,setup:true,theme:'light',accounts:[],categories:[{id:'food',name:'Alimentação',kind:'expense'}],dashboard:{availableBalanceCents:0,monthlyIncomeCents:0,monthlyExpenseCents:0,recentTransactions:[],hasNegativeBalance:false}}
function mockAPI(data:BootstrapData=empty){return {Bootstrap:vi.fn().mockResolvedValue(data),CompleteOnboarding:vi.fn().mockResolvedValue(profile),SkipOnboarding:vi.fn().mockResolvedValue(profile),CreateAccount:vi.fn().mockResolvedValue({}),UpdateAccount:vi.fn().mockResolvedValue({}),AdjustAccountBalance:vi.fn().mockResolvedValue({}),DeleteAccount:vi.fn().mockResolvedValue(undefined),CreateTransaction:vi.fn().mockResolvedValue({}),UpdateTransaction:vi.fn().mockResolvedValue({}),TrashTransaction:vi.fn().mockResolvedValue(undefined),RestoreTransaction:vi.fn().mockResolvedValue(undefined),DeleteTransactionPermanently:vi.fn().mockResolvedValue(undefined),EmptyTransactionTrash:vi.fn().mockResolvedValue(undefined),ListTransactions:vi.fn().mockResolvedValue([]),ListTrashedTransactions:vi.fn().mockResolvedValue([]),CreditCardsOverview:vi.fn().mockResolvedValue({cards:[],invoices:[]}),PayCreditCardInvoice:vi.fn().mockResolvedValue({}),ImportBankStatement:vi.fn().mockResolvedValue({bank:'itau',importedCount:2,duplicateCount:1,ignoredCount:0}),SetTheme:vi.fn().mockResolvedValue(profile),SetBalancesHidden:vi.fn().mockResolvedValue(profile),FixedExpensesOverview:vi.fn().mockResolvedValue({expenses:[],occurrences:[]}),CreateFixedExpense:vi.fn().mockResolvedValue({}),UpdateFixedExpense:vi.fn().mockResolvedValue({}),ArchiveFixedExpense:vi.fn().mockResolvedValue(undefined),RestoreFixedExpense:vi.fn().mockResolvedValue(undefined),ConfirmFixedExpenseOccurrence:vi.fn().mockResolvedValue({}),DismissFixedExpenseOccurrence:vi.fn().mockResolvedValue(undefined),ReopenFixedExpenseOccurrence:vi.fn().mockResolvedValue(undefined),GetUpdateStatus:vi.fn().mockResolvedValue({state:'disabled',currentVersion:'dev'}),CheckForUpdates:vi.fn().mockResolvedValue({state:'upToDate',currentVersion:'0.1.0'}),InstallUpdate:vi.fn().mockResolvedValue({state:'installing',currentVersion:'0.1.0',availableVersion:'0.2.0'})}}

test('permite pular onboarding sem criar dados financeiros',async()=>{const api=mockAPI({...empty,profile:null,setup:false,theme:''});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Fazer isso depois'}));expect(api.SkipOnboarding).toHaveBeenCalledOnce()})

test('conclui onboarding com conta e valor convertidos para centavos',async()=>{const api=mockAPI({...empty,profile:null,setup:false,theme:''});render(<App api={api}/>);await userEvent.type(await screen.findByRole('textbox',{name:'Como podemos chamar você?'}),'Ana');await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Principal');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'1.234,56');await userEvent.click(screen.getByRole('button',{name:/Começar agora/}));await waitFor(()=>expect(api.CompleteOnboarding).toHaveBeenCalledWith(expect.objectContaining({displayName:'Ana',firstAccount:expect.objectContaining({name:'Principal',openingBalanceCents:123456})})))})

test('aplica o tema escolhido ainda no onboarding',async()=>{render(<App api={mockAPI({...empty,profile:null,setup:false,theme:''})}/>);await userEvent.click(await screen.findByRole('radio',{name:/Gótico/}));expect(document.documentElement).toHaveAttribute('data-theme','gothic');expect(document.documentElement.style.colorScheme).toBe('dark')})

test('abre o dashboard no topo depois de concluir o onboarding',async()=>{const onboarding={...empty,profile:null,setup:false,theme:''} as BootstrapData;const api=mockAPI();api.Bootstrap.mockResolvedValueOnce(onboarding).mockResolvedValue(empty);const scrollTo=vi.spyOn(window,'scrollTo').mockImplementation(()=>{});render(<App api={api}/>);await userEvent.type(await screen.findByRole('textbox',{name:'Como podemos chamar você?'}),'Ana');await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Principal');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'100,00');await userEvent.click(screen.getByRole('button',{name:/Começar agora/}));expect(await screen.findByText('Disponível após despesas fixas')).toBeInTheDocument();expect(scrollTo).toHaveBeenCalledWith(0,0);scrollTo.mockRestore()})

test('orienta a criar conta no dashboard vazio',async()=>{render(<App api={mockAPI()}/>);expect(await screen.findByRole('heading',{name:'Crie sua primeira conta'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Criar conta'})).toBeEnabled()})

test('cria conta pela navegação funcional',async()=>{const api=mockAPI();render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Carteira');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'50,00');await userEvent.click(screen.getByRole('button',{name:'Criar conta'}));await waitFor(()=>expect(api.CreateAccount).toHaveBeenCalledWith(expect.objectContaining({name:'Carteira',openingBalanceCents:5000,type:'checking'})))})

test('cria cartão com limite, ciclo e fatura inicial opcional',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Adicionar'}));await userEvent.click(screen.getByRole('radio',{name:/Cartão de crédito/}));await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Nubank');await userEvent.type(screen.getByRole('textbox',{name:'Limite de crédito'}),'5.000,00');const days=screen.getAllByRole('spinbutton');await userEvent.type(days[0],'25');await userEvent.type(days[1],'2');await userEvent.type(screen.getByRole('textbox',{name:/Fatura já em aberto/}),'300,00');await userEvent.type(screen.getByLabelText('Vencimento dessa fatura'),'2026-09-02');await userEvent.click(screen.getByRole('button',{name:'Criar conta'}));await waitFor(()=>expect(api.CreateAccount).toHaveBeenCalledWith(expect.objectContaining({name:'Nubank',type:'credit_card',creditLimitCents:500000,closingDay:25,dueDay:2,openingDebtCents:30000})))})

const accountData:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:10000,currentBalanceCents:10000,openingDate:'2026-08-01',createdAt:'x'}],dashboard:{...empty.dashboard,availableBalanceCents:10000}}

test('registra ajuste de saldo com diferença, data e motivo',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Mais ações para Principal'}));await userEvent.click(screen.getByRole('menuitem',{name:'Ajustar saldo'}));expect(screen.getByText('Saldo atual')).toBeInTheDocument();const target=screen.getByRole('textbox',{name:/Saldo desejado/});await userEvent.clear(target);await userEvent.type(target,'80,00');expect(screen.getByText((_,element)=>element?.tagName==='DD'&&element.textContent?.includes('20,00')===true)).toBeInTheDocument();await userEvent.type(screen.getByRole('textbox',{name:'Motivo'}),'Conferência do extrato');await userEvent.click(screen.getByRole('button',{name:'Registrar ajuste'}));await waitFor(()=>expect(api.AdjustAccountBalance).toHaveBeenCalledWith('a',expect.objectContaining({targetBalanceCents:8000,reason:'Conferência do extrato'})))})

test('registra compra parcelada e paga parcialmente uma fatura',async()=>{const card={id:'card',name:'Nubank',type:'credit_card' as const,openingBalanceCents:0,currentBalanceCents:-30000,openingDate:'2026-08-01',createdAt:'x',creditLimitCents:500000,closingDay:25,dueDay:2};const data:BootstrapData={...accountData,accounts:[...accountData.accounts,card]};const invoice={id:'invoice',accountId:'card',accountName:'Nubank',referenceMonth:'2026-09',closingDate:'2026-08-25',dueDate:'2026-09-02',status:'open' as const,chargesCents:30000,carryForwardCents:0,paidCents:0,outstandingCents:30000,installments:[{id:'i',invoiceId:'invoice',transactionId:'t',description:'Notebook',amountCents:30000,installmentNumber:1,installmentCount:3}],payments:[]};const api=mockAPI(data);api.CreditCardsOverview.mockResolvedValue({cards:[{account:card,outstandingCents:30000,availableLimitCents:470000,currentInvoice:invoice}],invoices:[invoice]});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));const account=screen.getByRole('combobox',{name:'Conta'});await userEvent.clear(account);await userEvent.type(account,'Nubank');await userEvent.keyboard('{Home}{Enter}');await userEvent.type(screen.getByRole('textbox',{name:'Descrição'}),'Notebook');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'900,00');const installments=screen.getByRole('spinbutton',{name:'Parcelas'});await userEvent.clear(installments);await userEvent.type(installments,'3');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));await waitFor(()=>expect(api.CreateTransaction).toHaveBeenCalledWith(expect.objectContaining({accountId:'card',amountCents:90000,installmentCount:3})));await userEvent.click(screen.getByRole('button',{name:'Cartões e faturas'}));await screen.findByRole('heading',{name:'Faturas'});await userEvent.click(screen.getByRole('button',{name:'Pagar fatura'}));const amount=screen.getByRole('textbox',{name:/Valor do pagamento/});await userEvent.clear(amount);await userEvent.type(amount,'100,00');await userEvent.click(screen.getByRole('button',{name:'Confirmar pagamento'}));await waitFor(()=>expect(api.PayCreditCardInvoice).toHaveBeenCalledWith('invoice',expect.objectContaining({accountId:'a',amountCents:10000})))})

test('edita conta preenchida e devolve foco ao menu ao cancelar e salvar',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));const actions=screen.getByRole('button',{name:'Mais ações para Principal'});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));expect(screen.getByRole('heading',{name:'Revise os dados'})).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Nome da conta'})).toHaveValue('Principal');expect(screen.getByRole('textbox',{name:/Saldo inicial/})).toHaveValue('100,00');expect(screen.getByRole('radio',{name:/Conta corrente/})).toBeChecked();await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));await waitFor(()=>expect(actions).toHaveFocus());await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));const name=screen.getByRole('textbox',{name:'Nome da conta'});await userEvent.clear(name);await userEvent.type(name,'Casa');await userEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(api.UpdateAccount).toHaveBeenCalledWith('a',expect.objectContaining({name:'Casa',openingBalanceCents:10000,openingDate:'2026-08-01'})));await waitFor(()=>expect(actions).toHaveFocus())})

test('confirma ou cancela exclusão permanente de conta',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));const actions=screen.getByRole('button',{name:'Mais ações para Principal'});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(screen.getByRole('alertdialog')).toHaveTextContent('Esta ação é permanente');await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(api.DeleteAccount).not.toHaveBeenCalled();await waitFor(()=>expect(actions).toHaveFocus());await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));await waitFor(()=>expect(api.DeleteAccount).toHaveBeenCalledWith('a'))})

test('mantém conta e mostra bloqueio quando exclusão falha',async()=>{const api=mockAPI(accountData);api.DeleteAccount.mockRejectedValue(new Error('Esta conta possui movimentações e não pode ser removida.'));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Mais ações para Principal'}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));expect(await screen.findByRole('alert')).toHaveTextContent('possui movimentações');expect(screen.getByText('Principal')).toBeInTheDocument();expect(screen.getByRole('alertdialog')).toBeInTheDocument()})

test('excluir a última conta atualiza o estado vazio',async()=>{const api=mockAPI(accountData);api.Bootstrap.mockResolvedValueOnce(accountData).mockResolvedValue(empty);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Mais ações para Principal'}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));expect(await screen.findByRole('heading',{name:'Nenhuma conta ainda'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Criar conta'})).toBeEnabled()})

test('abre formulário de movimentação, foca descrição e envia centavos',async()=>{const data:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}]};const api=mockAPI(data);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));const description=screen.getByRole('textbox',{name:'Descrição'});expect(description).toHaveFocus();await userEvent.type(description,'Mercado');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'12,34');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));await waitFor(()=>expect(api.CreateTransaction).toHaveBeenCalledWith(expect.objectContaining({description:'Mercado',amountCents:1234,kind:'expense',accountId:'a'})))})

test('persiste escolha de tema pela fachada',async()=>{const api=mockAPI();render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));await userEvent.click(screen.getByRole('radio',{name:/Gótico/}));expect(api.SetTheme).toHaveBeenCalledWith('gothic')})

test('mostra e confirma uma atualização disponível',async()=>{const api=mockAPI();api.GetUpdateStatus.mockResolvedValue({state:'available',currentVersion:'0.1.0',availableVersion:'0.2.0',releaseNotes:'Correções importantes'});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Ver novidades'}));expect(screen.getByRole('dialog')).toHaveTextContent('Atualizar para 0.2.0');expect(screen.getByText('Correções importantes')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Baixar e instalar'}));expect(api.InstallUpdate).toHaveBeenCalledOnce()})

test('verifica atualização manualmente nas configurações',async()=>{const api=mockAPI();api.GetUpdateStatus.mockResolvedValue({state:'idle',currentVersion:'0.1.0'});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));await userEvent.click(screen.getByRole('button',{name:'Verificar agora'}));expect(api.CheckForUpdates).toHaveBeenCalledOnce()})

test('recolhe e expande a navegação sem perder seus destinos',async()=>{const user=userEvent.setup();render(<App api={mockAPI()}/>);const toggle=await screen.findByRole('button',{name:'Recolher navegação'});expect(toggle.querySelector('svg.icon')).toHaveAttribute('aria-hidden','true');expect(screen.queryByRole('contentinfo')).not.toBeInTheDocument();await user.click(toggle);expect(toggle).toHaveAccessibleName('Expandir navegação');expect(toggle.querySelector('svg.icon')).toHaveAttribute('aria-hidden','true');expect(screen.getByRole('button',{name:'Contas'})).toBeInTheDocument();await user.click(toggle);expect(toggle).toHaveAccessibleName('Recolher navegação')})

test('mantém um título principal por tela e remove rótulos repetidos',async()=>{
  const user=userEvent.setup();render(<App api={mockAPI(accountData)}/>);
  expect(await screen.findAllByRole('heading',{level:1})).toHaveLength(1);
  await user.click(screen.getByRole('button',{name:'Contas'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Contas'})).toBeInTheDocument();
  expect(screen.queryByText('Contas cadastradas')).not.toBeInTheDocument();
  expect(document.querySelector('.eyebrow')).toBeNull();
  await user.click(screen.getByRole('button',{name:'Movimentações'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Movimentações'})).toBeInTheDocument();
  expect(screen.queryByRole('heading',{name:'Todas as movimentações'})).not.toBeInTheDocument();
  await user.click(screen.getByRole('button',{name:'Despesas fixas'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Despesas fixas'})).toBeInTheDocument();
  expect(screen.queryByRole('heading',{level:2,name:'Despesas fixas'})).not.toBeInTheDocument();
  await user.click(screen.getByRole('button',{name:'Configurações'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Configurações'})).toBeInTheDocument();
  expect(screen.getByRole('heading',{name:'Escolha a atmosfera'})).toBeInTheDocument();
  expect(screen.queryByRole('contentinfo')).not.toBeInTheDocument();
})

test('inicia bloqueado e só carrega dados depois da senha correta',async()=>{const base=mockAPI();const api={...base,SecurityStatus:vi.fn().mockResolvedValue({enabled:true,locked:true}),UnlockDatabase:vi.fn().mockResolvedValue({enabled:true,locked:false})};render(<App api={api}/>);expect(await screen.findByRole('heading',{name:'Desbloqueie seu banco de dados'})).toBeInTheDocument();expect(base.Bootstrap).not.toHaveBeenCalled();await userEvent.type(screen.getByLabelText('Senha'),'senha-de-teste-segura');await userEvent.click(screen.getByRole('button',{name:'Desbloquear'}));expect(await screen.findByText('Disponível após despesas fixas')).toBeInTheDocument();expect(api.UnlockDatabase).toHaveBeenCalledWith({password:'senha-de-teste-segura'});expect(base.Bootstrap).toHaveBeenCalledOnce()})

test('expõe backup e exportações com aviso de texto puro',async()=>{const api={...mockAPI(),SecurityStatus:vi.fn().mockResolvedValue({enabled:false,locked:false}),BackupStatus:vi.fn().mockResolvedValue({folder:'/tmp/backups',defaultFolder:'/tmp/backups',automaticDue:false,nextDueAt:'2026-09-01T00:00:00Z'}),CreateBackup:vi.fn().mockResolvedValue({cancelled:true,success:false}),ExportData:vi.fn().mockResolvedValue({cancelled:true,success:false})};render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));expect(await screen.findByRole('heading',{name:'Backup e portabilidade'})).toBeInTheDocument();expect(screen.getByText(/CSV e JSON são arquivos em texto puro/)).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Criar backup agora'}));await waitFor(()=>expect(api.CreateBackup).toHaveBeenCalledOnce());expect(screen.queryByRole('alert')).not.toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Exportar CSV'}));expect(api.ExportData).toHaveBeenCalledWith('csv')})

test.each([
  [{enabled:false,locked:false},{enabled:true,locked:false},'Alterar senha'],
  [{enabled:true,locked:false},{enabled:false,locked:false},'Ativar criptografia'],
] as const)('atualiza a criptografia após restaurar backup',async(initial,restored,expectedAction)=>{
  const api={...mockAPI(),SecurityStatus:vi.fn().mockResolvedValueOnce(initial).mockResolvedValueOnce(restored),BackupStatus:vi.fn().mockResolvedValue({folder:'/tmp/backups',defaultFolder:'/tmp/backups',automaticDue:false}),InspectBackup:vi.fn().mockResolvedValue({success:true,cancelled:false,backup:{path:'/tmp/restore.cashbackup',manifest:{formatVersion:1,createdAt:'2026-08-01T12:00:00Z',applicationVersion:'0.1.0',schemaVersion:6,encrypted:restored.enabled,payloadSha256:'hash',kind:'manual'}}}),RestoreBackup:vi.fn().mockResolvedValue({success:true,cancelled:false,backup:{}})}
  render(<App api={api}/>)
  await userEvent.click(await screen.findByRole('button',{name:'Configurações'}))
  await userEvent.click(await screen.findByRole('button',{name:'Restaurar backup'}))
  await userEvent.click(await screen.findByRole('button',{name:'Restaurar e substituir'}))
  await waitFor(()=>expect(api.SecurityStatus).toHaveBeenCalledTimes(2))
  expect(api.Bootstrap).toHaveBeenCalledTimes(2)
  await userEvent.click(screen.getByRole('button',{name:'Configurações'}))
  expect(await screen.findByRole('button',{name:expectedAction})).toBeInTheDocument()
})

test('mantém o estado de segurança quando a restauração falha',async()=>{
  const api={...mockAPI(),SecurityStatus:vi.fn().mockResolvedValue({enabled:false,locked:false}),BackupStatus:vi.fn().mockResolvedValue({folder:'/tmp/backups',defaultFolder:'/tmp/backups',automaticDue:false}),InspectBackup:vi.fn().mockResolvedValue({success:true,cancelled:false,backup:{path:'/tmp/restore.cashbackup',manifest:{formatVersion:1,createdAt:'2026-08-01T12:00:00Z',applicationVersion:'0.1.0',schemaVersion:6,encrypted:false,payloadSha256:'hash',kind:'manual'}}}),RestoreBackup:vi.fn().mockRejectedValue(new Error('Backup inválido'))}
  render(<App api={api}/>)
  await userEvent.click(await screen.findByRole('button',{name:'Configurações'}))
  await userEvent.click(await screen.findByRole('button',{name:'Restaurar backup'}))
  await userEvent.click(await screen.findByRole('button',{name:'Restaurar e substituir'}))
  expect(await screen.findByRole('alert')).toHaveTextContent('Backup inválido')
  expect(api.SecurityStatus).toHaveBeenCalledOnce()
  expect(api.Bootstrap).toHaveBeenCalledOnce()
})

test('exige confirmação de que a chave de recuperação foi salva',async()=>{const api={...mockAPI(),SecurityStatus:vi.fn().mockResolvedValue({enabled:false,locked:false}),EnableEncryption:vi.fn().mockResolvedValue({status:{enabled:true,locked:false},recoveryKey:'ABCDE-FGHIJ-KLMNO'}),BackupStatus:vi.fn().mockResolvedValue({folder:'/tmp/backups',defaultFolder:'/tmp/backups',automaticDue:true})};render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));await userEvent.click(await screen.findByRole('button',{name:'Ativar criptografia'}));await userEvent.type(screen.getByLabelText('Nova senha'),'senha-de-teste-segura');await userEvent.type(screen.getByLabelText('Confirme a senha'),'senha-de-teste-segura');await userEvent.click(screen.getByRole('button',{name:'Criptografar banco'}));expect(await screen.findByText('ABCDE-FGHIJ-KLMNO')).toBeInTheDocument();const finish=screen.getByRole('button',{name:'Concluir'});expect(finish).toBeDisabled();await userEvent.click(screen.getByRole('checkbox',{name:'Salvei a chave em um local seguro'}));expect(finish).toBeEnabled()})

test('mostra atividade recente com sinais não dependentes de cor',async()=>{const data:BootstrapData={...empty,dashboard:{...empty.dashboard,recentTransactions:[{id:'t',kind:'expense',amountCents:1290,accountId:'a',accountName:'Principal',description:'Almoço',occurrenceDate:'2026-08-16',createdAt:'x',updatedAt:'x'}]}};render(<App api={mockAPI(data)}/>);expect(await screen.findByText('Almoço')).toBeInTheDocument();expect(screen.getByText('Despesa:')).toBeInTheDocument();expect(screen.getByText(/R\$\s*12,90/)).toBeInTheDocument()})

test('importa extratos aceitos com carregamento, deduplicação e origem visível',async()=>{const imported={...transaction,automaticImport:true,importBank:'itau' as const};const api=mockAPI({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[imported]}});api.ListTransactions.mockResolvedValue([imported]);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Movimentações'}));expect(await screen.findByText('Importação automática')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Importar extrato'}));const input=screen.getByLabelText(/Arquivo do extrato/) as HTMLInputElement;expect(input.accept).toContain('.pdf');expect(input.accept).toContain('.ofx');expect(input.accept).toContain('.csv');const file=new File(['Data;Descrição;Valor\n01/08/2026;Salário;+100,00'],'itau-agosto.csv',{type:'text/csv'});await userEvent.upload(input,file);await userEvent.click(screen.getByRole('button',{name:'Importar movimentações'}));await waitFor(()=>expect(api.ImportBankStatement).toHaveBeenCalledWith(expect.objectContaining({accountId:'a',bank:'itau',fileName:'itau-agosto.csv',base64Data:expect.any(String)})));expect(await screen.findByRole('status')).toHaveTextContent('2 movimentações adicionadas · 1 repetida ignorada')})

test('valida o formato e mantém a falha de importação como texto seguro',async()=>{const api=mockAPI(transactionData);let fail!:(reason?:unknown)=>void;api.ImportBankStatement.mockReturnValue(new Promise((_,reject)=>{fail=reject}));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Movimentações'}));await userEvent.click(screen.getByRole('button',{name:'Importar extrato'}));await userEvent.click(screen.getByRole('button',{name:'Importar movimentações'}));expect(screen.getByRole('alert')).toHaveTextContent('Escolha um arquivo PDF, OFX ou CSV.');const input=screen.getByLabelText(/Arquivo do extrato/);await userEvent.upload(input,new File(['OFXHEADER:100'],'agosto.ofx',{type:'application/x-ofx'}));await userEvent.click(screen.getByRole('button',{name:'Importar movimentações'}));expect(await screen.findByLabelText('Importando extrato')).toBeInTheDocument();fail(new Error('<img src=x onerror=alert(1)>'));expect(await screen.findByRole('alert')).toHaveTextContent('<img src=x onerror=alert(1)>');expect(screen.queryByRole('img')).not.toBeInTheDocument()})

test('atalho global abre e Escape fecha a movimentação',async()=>{const data:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}]};render(<App api={mockAPI(data)}/>);await screen.findByText('Disponível após despesas fixas');window.dispatchEvent(new KeyboardEvent('keydown',{key:'n',ctrlKey:true}));expect(await screen.findByRole('dialog')).toBeInTheDocument();window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument())})

test('mostra falha de bootstrap e permite tentar novamente',async()=>{const api=mockAPI();api.Bootstrap.mockRejectedValueOnce(new Error('Falha segura'));render(<App api={api}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Falha segura');await userEvent.click(screen.getByRole('button',{name:'Tentar novamente'}));expect(await screen.findByText('Disponível após despesas fixas')).toBeInTheDocument()})

test('combobox filtra sem acentos e oferece navegação por teclado',async()=>{const user=userEvent.setup();const change=vi.fn();render(<SearchCombobox label="Categoria" options={[{id:'education',label:'Educação'},{id:'food',label:'Alimentação'}]} value="" onChange={change}/>);const input=screen.getByRole('combobox',{name:'Categoria'});await user.type(input,'educacao');expect(screen.getByRole('option',{name:'Educação'})).toBeInTheDocument();await user.keyboard('{Home}{Enter}');expect(change).toHaveBeenLastCalledWith('education');expect(input).toHaveValue('Educação')})

test('registra transferência com origem e destino pesquisáveis',async()=>{const accounts=[{id:'a',name:'Principal',type:'checking' as const,openingBalanceCents:10000,currentBalanceCents:10000,openingDate:'2026-08-01',createdAt:'x'},{id:'b',name:'Reserva',type:'savings' as const,openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}];const data={...empty,accounts};const api=mockAPI(data);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));await userEvent.click(screen.getByRole('radio',{name:'Transferência'}));const destination=screen.getByRole('combobox',{name:'Conta de destino'});await userEvent.type(destination,'reserva');await userEvent.keyboard('{Home}{Enter}');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'25,00');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));await waitFor(()=>expect(api.CreateTransaction).toHaveBeenCalledWith(expect.objectContaining({kind:'transfer',amountCents:2500,accountId:'a',destinationAccountId:'b',categoryId:'',description:''})))})

const transaction:Transaction={id:'t',kind:'expense',amountCents:1290,accountId:'a',accountName:'Principal',categoryId:'food',categoryName:'Alimentação',description:'Almoço',occurrenceDate:'2026-08-16',createdAt:'x',updatedAt:'x'}
const transactionData:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:10000,currentBalanceCents:8710,openingDate:'2026-08-01',createdAt:'x'}],dashboard:{...empty.dashboard,recentTransactions:[transaction],availableBalanceCents:8710,monthlyExpenseCents:1290}}

test('mantém a movimentação aberta enquanto o salvamento está em curso',async()=>{const api=mockAPI(transactionData);let finish!:()=>void;api.CreateTransaction.mockImplementationOnce(()=>new Promise(resolve=>{finish=()=>resolve(transaction)}));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));await userEvent.type(screen.getByRole('textbox',{name:'Descrição'}),'Mercado');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'12,90');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));expect(screen.getByRole('button',{name:'Salvando…'})).toBeDisabled();window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));expect(screen.getByRole('dialog')).toBeInTheDocument();finish();await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument())})

test('abre edição preenchida, salva e devolve foco ao menu de ações',async()=>{const api=mockAPI(transactionData);render(<App api={api}/>);const actions=await screen.findByRole('button',{name:/Mais ações para Almoço/});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));expect(screen.getByRole('heading',{name:'Editar registro'})).toBeInTheDocument();const description=screen.getByRole('textbox',{name:'Descrição'});expect(description).toHaveValue('Almoço');await userEvent.clear(description);await userEvent.type(description,'Jantar');await userEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(api.UpdateTransaction).toHaveBeenCalledWith('t',expect.objectContaining({description:'Jantar',amountCents:1290})));await waitFor(()=>expect(actions).toHaveFocus())})

test('remove otimisticamente, devolve o foco e permite desfazer',async()=>{const api=mockAPI(transactionData);api.Bootstrap.mockResolvedValueOnce(transactionData).mockResolvedValue({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[]}});render(<App api={api}/>);const actions=await screen.findByRole('button',{name:/Mais ações para Almoço/});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(screen.queryByText('Almoço')).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('Movimentação removida');await waitFor(()=>expect(screen.getByRole('button',{name:/Nova movimentação/})).toHaveFocus());await userEvent.click(screen.getByRole('button',{name:'Desfazer'}));expect(api.RestoreTransaction).toHaveBeenCalledWith('t')})

test('restaura a linha quando a remoção falha',async()=>{const api=mockAPI(transactionData);api.TrashTransaction.mockRejectedValue(new Error('Não foi possível remover.'));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Mais ações para Almoço/}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(await screen.findByText('Almoço')).toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível remover.')})

test('lista a lixeira persistente e restaura uma movimentação',async()=>{const trashed={...transaction,deletedAt:'2026-08-16T15:00:00Z'};const api=mockAPI(transactionData);api.ListTrashedTransactions.mockResolvedValue([trashed]);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Movimentações'}));await userEvent.click(screen.getByRole('tab',{name:/Lixeira/}));expect(await screen.findByText('Removida em 16/08/2026, 12:00')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Restaurar'}));await waitFor(()=>expect(api.RestoreTransaction).toHaveBeenCalledWith('t'));expect(screen.queryByText('Almoço')).not.toBeInTheDocument()})

test('confirma exclusão individual e esvaziamento da lixeira',async()=>{const lunch={...transaction,deletedAt:'2026-08-16T15:00:00Z'},market={...transaction,id:'market',description:'Mercado',deletedAt:'2026-08-16T16:00:00Z'};const api=mockAPI(transactionData);api.ListTrashedTransactions.mockResolvedValue([market,lunch]);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Movimentações'}));await userEvent.click(screen.getByRole('tab',{name:/Lixeira/}));await screen.findByText('Mercado');const individual=screen.getAllByRole('button',{name:'Excluir'})[0];await userEvent.click(individual);expect(screen.getByRole('alertdialog')).toHaveTextContent('Excluir “Mercado” permanentemente?');await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(api.DeleteTransactionPermanently).not.toHaveBeenCalled();await waitFor(()=>expect(individual).toHaveFocus());await userEvent.click(individual);await userEvent.click(screen.getByRole('button',{name:'Excluir permanentemente'}));await waitFor(()=>expect(api.DeleteTransactionPermanently).toHaveBeenCalledWith('market'));await userEvent.click(screen.getByRole('button',{name:'Esvaziar lixeira'}));const dialog=screen.getByRole('alertdialog');expect(dialog).toHaveTextContent('1 movimentação');await userEvent.click(within(dialog).getByRole('button',{name:'Esvaziar lixeira'}));await waitFor(()=>expect(api.EmptyTransactionTrash).toHaveBeenCalledOnce());expect(await screen.findByRole('heading',{name:'A lixeira está vazia'})).toBeInTheDocument()})

test('transferência usa rótulo e valor neutros sem depender de cor',async()=>{const transfer={...transaction,kind:'transfer' as const,description:'Transferência para Reserva',destinationAccountId:'b',destinationAccountName:'Reserva',categoryId:undefined,categoryName:undefined};render(<App api={mockAPI({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[transfer]}})}/>);expect(await screen.findByText('Principal para Reserva')).toBeInTheDocument();const label=screen.getByText('Transferência:');expect(label.parentElement).toHaveClass('transfer');expect(label.parentElement?.textContent).not.toMatch(/[+−]/)})

test('oculta saldos da dashboard sem ocultar valores de movimentação',async()=>{const data:BootstrapData={...transactionData,profile:{...profile,balancesHidden:false},dashboard:{...transactionData.dashboard,totalBalanceCents:8710,pendingFixedExpensesCents:0,balanceHistory:[{month:'2026-02',label:'fev.',balanceCents:7000},{month:'2026-08',label:'ago.',balanceCents:8710}],accountAllocations:[{accountId:'a',accountName:'Principal',balanceCents:8710}]}};const api=mockAPI(data);render(<App api={api}/>);expect(await screen.findByText('Evolução do saldo')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Ocultar saldos'}));expect(api.SetBalancesHidden).toHaveBeenCalledWith(true);expect(screen.getAllByText('Saldos ocultos')).toHaveLength(2);expect(screen.getByText('Almoço')).toBeInTheDocument();expect(screen.getAllByText(/R\$\s*12,90/).length).toBeGreaterThan(0)})

test('cria despesa fixa pela navegação e confirma uma previsão com valor real',async()=>{const occurrence={id:'o',fixedExpenseId:'f',referenceMonth:'2026-08',dueDate:'2026-08-20',description:'Internet',expectedAmountCents:9990,accountId:'a',accountName:'Principal',categoryId:'bills',categoryName:'Contas',status:'pending' as const,createdAt:'x',updatedAt:'x'};const expense={id:'f',description:'Internet',amountCents:9990,dueDay:20,accountId:'a',accountName:'Principal',categoryId:'bills',categoryName:'Contas',createdAt:'x',updatedAt:'x'};const data:BootstrapData={...accountData,categories:[...empty.categories,{id:'bills',name:'Contas',kind:'expense'}]};const api=mockAPI(data);api.FixedExpensesOverview.mockResolvedValue({expenses:[expense],occurrences:[occurrence]});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Despesas fixas'}));expect(await screen.findByText('O que falta pagar')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:/Confirmar/}));const value=screen.getByRole('textbox',{name:'Valor pago'});await userEvent.clear(value);await userEvent.type(value,'105,00');await userEvent.click(screen.getByRole('button',{name:'Confirmar pagamento'}));await waitFor(()=>expect(api.ConfirmFixedExpenseOccurrence).toHaveBeenCalledWith('o',expect.objectContaining({amountCents:10500})));await userEvent.click(screen.getByRole('button',{name:'Adicionar'}));await userEvent.type(screen.getByRole('textbox',{name:'Descrição'}),'Aluguel');await userEvent.type(screen.getByRole('textbox',{name:'Valor estimado'}),'1200,00');await userEvent.type(screen.getByRole('spinbutton',{name:'Dia do vencimento'}),'10');const category=screen.getByRole('combobox',{name:'Categoria'});await userEvent.type(category,'contas');await userEvent.keyboard('{Home}{Enter}');await userEvent.click(screen.getByRole('button',{name:'Criar despesa fixa'}));await waitFor(()=>expect(api.CreateFixedExpense).toHaveBeenCalledWith(expect.objectContaining({description:'Aluguel',amountCents:120000,dueDay:10,accountId:'a',categoryId:'bills'})))})
