import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { expect, test, vi } from 'vitest'
import App from './App'
import { SearchCombobox } from './components'
import type { BootstrapData, Profile, Transaction } from './types'

const profile: Profile={displayName:'Ana',currency:'BRL',theme:'light',onboardingStatus:'completed'}
const empty:BootstrapData={profile,setup:true,theme:'light',accounts:[],categories:[{id:'food',name:'Alimentação',kind:'expense'}],dashboard:{availableBalanceCents:0,monthlyIncomeCents:0,monthlyExpenseCents:0,recentTransactions:[],hasNegativeBalance:false}}
function mockAPI(data:BootstrapData=empty){return {Bootstrap:vi.fn().mockResolvedValue(data),CompleteOnboarding:vi.fn().mockResolvedValue(profile),SkipOnboarding:vi.fn().mockResolvedValue(profile),CreateAccount:vi.fn().mockResolvedValue({}),UpdateAccount:vi.fn().mockResolvedValue({}),DeleteAccount:vi.fn().mockResolvedValue(undefined),CreateTransaction:vi.fn().mockResolvedValue({}),UpdateTransaction:vi.fn().mockResolvedValue({}),TrashTransaction:vi.fn().mockResolvedValue(undefined),RestoreTransaction:vi.fn().mockResolvedValue(undefined),ListTransactions:vi.fn().mockResolvedValue([]),ImportBankStatement:vi.fn().mockResolvedValue({bank:'itau',importedCount:2,duplicateCount:1,ignoredCount:0}),SetTheme:vi.fn().mockResolvedValue(profile),SetBalancesHidden:vi.fn().mockResolvedValue(profile),FixedExpensesOverview:vi.fn().mockResolvedValue({expenses:[],occurrences:[]}),CreateFixedExpense:vi.fn().mockResolvedValue({}),UpdateFixedExpense:vi.fn().mockResolvedValue({}),ArchiveFixedExpense:vi.fn().mockResolvedValue(undefined),RestoreFixedExpense:vi.fn().mockResolvedValue(undefined),ConfirmFixedExpenseOccurrence:vi.fn().mockResolvedValue({}),DismissFixedExpenseOccurrence:vi.fn().mockResolvedValue(undefined),ReopenFixedExpenseOccurrence:vi.fn().mockResolvedValue(undefined),GetUpdateStatus:vi.fn().mockResolvedValue({state:'disabled',currentVersion:'dev'}),CheckForUpdates:vi.fn().mockResolvedValue({state:'upToDate',currentVersion:'0.1.0'}),InstallUpdate:vi.fn().mockResolvedValue({state:'installing',currentVersion:'0.1.0',availableVersion:'0.2.0'})}}

test('permite pular onboarding sem criar dados financeiros',async()=>{const api=mockAPI({...empty,profile:null,setup:false,theme:''});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Fazer isso depois'}));expect(api.SkipOnboarding).toHaveBeenCalledOnce()})

test('conclui onboarding com conta e valor convertidos para centavos',async()=>{const api=mockAPI({...empty,profile:null,setup:false,theme:''});render(<App api={api}/>);await userEvent.type(await screen.findByRole('textbox',{name:'Como podemos chamar você?'}),'Ana');await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Principal');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'1.234,56');await userEvent.click(screen.getByRole('button',{name:/Começar agora/}));await waitFor(()=>expect(api.CompleteOnboarding).toHaveBeenCalledWith(expect.objectContaining({displayName:'Ana',firstAccount:expect.objectContaining({name:'Principal',openingBalanceCents:123456})})))})

test('aplica o tema escolhido ainda no onboarding',async()=>{render(<App api={mockAPI({...empty,profile:null,setup:false,theme:''})}/>);await userEvent.click(await screen.findByRole('radio',{name:/Gótico/}));expect(document.documentElement).toHaveAttribute('data-theme','gothic');expect(document.documentElement.style.colorScheme).toBe('dark')})

test('abre o dashboard no topo depois de concluir o onboarding',async()=>{const onboarding={...empty,profile:null,setup:false,theme:''} as BootstrapData;const api=mockAPI();api.Bootstrap.mockResolvedValueOnce(onboarding).mockResolvedValue(empty);const scrollTo=vi.spyOn(window,'scrollTo').mockImplementation(()=>{});render(<App api={api}/>);await userEvent.type(await screen.findByRole('textbox',{name:'Como podemos chamar você?'}),'Ana');await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Principal');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'100,00');await userEvent.click(screen.getByRole('button',{name:/Começar agora/}));expect(await screen.findByText('Disponível após despesas fixas')).toBeInTheDocument();expect(scrollTo).toHaveBeenCalledWith(0,0);scrollTo.mockRestore()})

test('orienta a criar conta no dashboard vazio',async()=>{render(<App api={mockAPI()}/>);expect(await screen.findByRole('heading',{name:'Crie sua primeira conta'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Criar conta'})).toBeEnabled()})

test('cria conta pela navegação funcional',async()=>{const api=mockAPI();render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.type(screen.getByRole('textbox',{name:'Nome da conta'}),'Carteira');await userEvent.type(screen.getByRole('textbox',{name:/Saldo inicial/}),'50,00');await userEvent.click(screen.getByRole('button',{name:'Criar conta'}));await waitFor(()=>expect(api.CreateAccount).toHaveBeenCalledWith(expect.objectContaining({name:'Carteira',openingBalanceCents:5000,type:'checking'})))})

const accountData:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:10000,currentBalanceCents:10000,openingDate:'2026-08-01',createdAt:'x'}],dashboard:{...empty.dashboard,availableBalanceCents:10000}}

test('edita conta preenchida e devolve foco ao menu ao cancelar e salvar',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));const actions=screen.getByRole('button',{name:'Mais ações para Principal'});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));expect(screen.getByRole('heading',{name:'Revise os dados'})).toBeInTheDocument();expect(screen.getByRole('textbox',{name:'Nome da conta'})).toHaveValue('Principal');expect(screen.getByRole('textbox',{name:/Saldo inicial/})).toHaveValue('100,00');expect(screen.getByRole('radio',{name:/Conta corrente/})).toBeChecked();await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));await waitFor(()=>expect(actions).toHaveFocus());await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));const name=screen.getByRole('textbox',{name:'Nome da conta'});await userEvent.clear(name);await userEvent.type(name,'Casa');await userEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(api.UpdateAccount).toHaveBeenCalledWith('a',expect.objectContaining({name:'Casa',openingBalanceCents:10000,openingDate:'2026-08-01'})));await waitFor(()=>expect(actions).toHaveFocus())})

test('confirma ou cancela exclusão permanente de conta',async()=>{const api=mockAPI(accountData);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));const actions=screen.getByRole('button',{name:'Mais ações para Principal'});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(screen.getByRole('alertdialog')).toHaveTextContent('Esta ação é permanente');await userEvent.click(screen.getByRole('button',{name:'Cancelar'}));expect(api.DeleteAccount).not.toHaveBeenCalled();await waitFor(()=>expect(actions).toHaveFocus());await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));await waitFor(()=>expect(api.DeleteAccount).toHaveBeenCalledWith('a'))})

test('mantém conta e mostra bloqueio quando exclusão falha',async()=>{const api=mockAPI(accountData);api.DeleteAccount.mockRejectedValue(new Error('Esta conta possui movimentações e não pode ser removida.'));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Mais ações para Principal'}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));expect(await screen.findByRole('alert')).toHaveTextContent('possui movimentações');expect(screen.getByText('Principal')).toBeInTheDocument();expect(screen.getByRole('alertdialog')).toBeInTheDocument()})

test('excluir a última conta atualiza o estado vazio',async()=>{const api=mockAPI(accountData);api.Bootstrap.mockResolvedValueOnce(accountData).mockResolvedValue(empty);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Contas'}));await userEvent.click(screen.getByRole('button',{name:'Mais ações para Principal'}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));await userEvent.click(screen.getByRole('button',{name:'Remover permanentemente'}));expect(await screen.findByRole('heading',{name:'Nenhuma conta ainda'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Criar conta'})).toBeEnabled()})

test('abre formulário de movimentação, foca descrição e envia centavos',async()=>{const data:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}]};const api=mockAPI(data);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));const description=screen.getByRole('textbox',{name:'Descrição'});expect(description).toHaveFocus();await userEvent.type(description,'Mercado');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'12,34');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));await waitFor(()=>expect(api.CreateTransaction).toHaveBeenCalledWith(expect.objectContaining({description:'Mercado',amountCents:1234,kind:'expense',accountId:'a'})))})

test('persiste escolha de tema pela fachada',async()=>{const api=mockAPI();render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));await userEvent.click(screen.getByRole('radio',{name:/Gótico/}));expect(api.SetTheme).toHaveBeenCalledWith('gothic')})

test('mostra e confirma uma atualização disponível',async()=>{const api=mockAPI();api.GetUpdateStatus.mockResolvedValue({state:'available',currentVersion:'0.1.0',availableVersion:'0.2.0',releaseNotes:'Correções importantes'});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Ver novidades'}));expect(screen.getByRole('dialog')).toHaveTextContent('Atualizar para 0.2.0');expect(screen.getByText('Correções importantes')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Baixar e instalar'}));expect(api.InstallUpdate).toHaveBeenCalledOnce()})

test('verifica atualização manualmente nas configurações',async()=>{const api=mockAPI();api.GetUpdateStatus.mockResolvedValue({state:'idle',currentVersion:'0.1.0'});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Configurações'}));await userEvent.click(screen.getByRole('button',{name:'Verificar agora'}));expect(api.CheckForUpdates).toHaveBeenCalledOnce()})

test('recolhe e expande a navegação sem perder seus destinos',async()=>{const user=userEvent.setup();render(<App api={mockAPI()}/>);const toggle=await screen.findByRole('button',{name:'Recolher navegação'});expect(toggle.querySelector('svg.icon')).toHaveAttribute('aria-hidden','true');expect(screen.queryByRole('contentinfo')).not.toBeInTheDocument();await user.click(toggle);expect(toggle).toHaveAccessibleName('Expandir navegação');expect(toggle.querySelector('svg.icon')).toHaveAttribute('aria-hidden','true');expect(screen.getByRole('button',{name:'Contas'})).toBeInTheDocument();await user.click(toggle);expect(toggle).toHaveAccessibleName('Recolher navegação')})

test('mantém um título principal por tela e remove rótulos repetidos',async()=>{
  const user=userEvent.setup();render(<App api={mockAPI(accountData)}/>);
  expect(await screen.findAllByRole('heading',{level:1})).toHaveLength(1);
  await user.click(screen.getByRole('button',{name:'Contas'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Contas'})).toBeInTheDocument();
  expect(screen.queryByText('Contas cadastradas')).not.toBeInTheDocument();
  expect(document.querySelector('.eyebrow')).toBeNull();
  await user.click(screen.getByRole('button',{name:'Movimentações'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Movimentações'})).toBeInTheDocument();
  expect(screen.queryByRole('heading',{name:'Todas as movimentações'})).not.toBeInTheDocument();
  await user.click(screen.getByRole('button',{name:'Despesas fixas'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Despesas fixas'})).toBeInTheDocument();
  expect(screen.queryByRole('heading',{level:2,name:'Despesas fixas'})).not.toBeInTheDocument();
  await user.click(screen.getByRole('button',{name:'Configurações'}));
  expect(screen.getAllByRole('heading',{level:1})).toHaveLength(1);
  expect(screen.getByRole('heading',{level:1,name:'Configurações'})).toBeInTheDocument();
  expect(screen.getByRole('heading',{name:'Escolha a atmosfera'})).toBeInTheDocument();
  expect(screen.queryByRole('contentinfo')).not.toBeInTheDocument();
})

test('mostra atividade recente com sinais não dependentes de cor',async()=>{const data:BootstrapData={...empty,dashboard:{...empty.dashboard,recentTransactions:[{id:'t',kind:'expense',amountCents:1290,accountId:'a',accountName:'Principal',description:'Almoço',occurrenceDate:'2026-08-16',createdAt:'x',updatedAt:'x'}]}};render(<App api={mockAPI(data)}/>);expect(await screen.findByText('Almoço')).toBeInTheDocument();expect(screen.getByText('Despesa:')).toBeInTheDocument();expect(screen.getByText(/R\$\s*12,90/)).toBeInTheDocument()})

test('importa extrato PDF com carregamento, deduplicação e origem visível',async()=>{const imported={...transaction,automaticImport:true,importBank:'itau' as const};const api=mockAPI({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[imported]}});api.ListTransactions.mockResolvedValue([imported]);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Movimentações'}));expect(await screen.findByText('Importação automática')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Importar extrato PDF'}));const file=new File(['%PDF-1.4 teste'],'itau-agosto.pdf',{type:'application/pdf'});await userEvent.upload(screen.getByLabelText(/Arquivo PDF/),file);await userEvent.click(screen.getByRole('button',{name:'Importar movimentações'}));await waitFor(()=>expect(api.ImportBankStatement).toHaveBeenCalledWith(expect.objectContaining({accountId:'a',bank:'itau',fileName:'itau-agosto.pdf',base64Pdf:expect.any(String)})));expect(await screen.findByRole('status')).toHaveTextContent('2 movimentações adicionadas · 1 repetida ignorada')})

test('atalho global abre e Escape fecha a movimentação',async()=>{const data:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}]};render(<App api={mockAPI(data)}/>);await screen.findByText('Disponível após despesas fixas');window.dispatchEvent(new KeyboardEvent('keydown',{key:'n',ctrlKey:true}));expect(await screen.findByRole('dialog')).toBeInTheDocument();window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument())})

test('mostra falha de bootstrap e permite tentar novamente',async()=>{const api=mockAPI();api.Bootstrap.mockRejectedValueOnce(new Error('Falha segura'));render(<App api={api}/>);expect(await screen.findByRole('alert')).toHaveTextContent('Falha segura');await userEvent.click(screen.getByRole('button',{name:'Tentar novamente'}));expect(await screen.findByText('Disponível após despesas fixas')).toBeInTheDocument()})

test('combobox filtra sem acentos e oferece navegação por teclado',async()=>{const user=userEvent.setup();const change=vi.fn();render(<SearchCombobox label="Categoria" options={[{id:'education',label:'Educação'},{id:'food',label:'Alimentação'}]} value="" onChange={change}/>);const input=screen.getByRole('combobox',{name:'Categoria'});await user.type(input,'educacao');expect(screen.getByRole('option',{name:'Educação'})).toBeInTheDocument();await user.keyboard('{Home}{Enter}');expect(change).toHaveBeenLastCalledWith('education');expect(input).toHaveValue('Educação')})

test('registra transferência com origem e destino pesquisáveis',async()=>{const accounts=[{id:'a',name:'Principal',type:'checking' as const,openingBalanceCents:10000,currentBalanceCents:10000,openingDate:'2026-08-01',createdAt:'x'},{id:'b',name:'Reserva',type:'savings' as const,openingBalanceCents:0,currentBalanceCents:0,openingDate:'2026-08-01',createdAt:'x'}];const data={...empty,accounts};const api=mockAPI(data);render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));await userEvent.click(screen.getByRole('radio',{name:'Transferência'}));const destination=screen.getByRole('combobox',{name:'Conta de destino'});await userEvent.type(destination,'reserva');await userEvent.keyboard('{Home}{Enter}');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'25,00');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));await waitFor(()=>expect(api.CreateTransaction).toHaveBeenCalledWith(expect.objectContaining({kind:'transfer',amountCents:2500,accountId:'a',destinationAccountId:'b',categoryId:'',description:''})))})

const transaction:Transaction={id:'t',kind:'expense',amountCents:1290,accountId:'a',accountName:'Principal',categoryId:'food',categoryName:'Alimentação',description:'Almoço',occurrenceDate:'2026-08-16',createdAt:'x',updatedAt:'x'}
const transactionData:BootstrapData={...empty,accounts:[{id:'a',name:'Principal',type:'checking',openingBalanceCents:10000,currentBalanceCents:8710,openingDate:'2026-08-01',createdAt:'x'}],dashboard:{...empty.dashboard,recentTransactions:[transaction],availableBalanceCents:8710,monthlyExpenseCents:1290}}

test('mantém a movimentação aberta enquanto o salvamento está em curso',async()=>{const api=mockAPI(transactionData);let finish!:()=>void;api.CreateTransaction.mockImplementationOnce(()=>new Promise(resolve=>{finish=()=>resolve(transaction)}));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Nova movimentação/}));await userEvent.type(screen.getByRole('textbox',{name:'Descrição'}),'Mercado');await userEvent.type(screen.getByRole('textbox',{name:/Valor/}),'12,90');await userEvent.click(screen.getByRole('button',{name:'Registrar'}));expect(screen.getByRole('button',{name:'Salvando…'})).toBeDisabled();window.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape'}));expect(screen.getByRole('dialog')).toBeInTheDocument();finish();await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument())})

test('abre edição preenchida, salva e devolve foco ao menu de ações',async()=>{const api=mockAPI(transactionData);render(<App api={api}/>);const actions=await screen.findByRole('button',{name:/Mais ações para Almoço/});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Editar'}));expect(screen.getByRole('heading',{name:'Editar registro'})).toBeInTheDocument();const description=screen.getByRole('textbox',{name:'Descrição'});expect(description).toHaveValue('Almoço');await userEvent.clear(description);await userEvent.type(description,'Jantar');await userEvent.click(screen.getByRole('button',{name:'Salvar alterações'}));await waitFor(()=>expect(api.UpdateTransaction).toHaveBeenCalledWith('t',expect.objectContaining({description:'Jantar',amountCents:1290})));await waitFor(()=>expect(actions).toHaveFocus())})

test('remove otimisticamente, devolve o foco e permite desfazer',async()=>{const api=mockAPI(transactionData);api.Bootstrap.mockResolvedValueOnce(transactionData).mockResolvedValue({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[]}});render(<App api={api}/>);const actions=await screen.findByRole('button',{name:/Mais ações para Almoço/});await userEvent.click(actions);await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(screen.queryByText('Almoço')).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('Movimentação removida');await waitFor(()=>expect(screen.getByRole('button',{name:/Nova movimentação/})).toHaveFocus());await userEvent.click(screen.getByRole('button',{name:'Desfazer'}));expect(api.RestoreTransaction).toHaveBeenCalledWith('t')})

test('restaura a linha quando a remoção falha',async()=>{const api=mockAPI(transactionData);api.TrashTransaction.mockRejectedValue(new Error('Não foi possível remover.'));render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:/Mais ações para Almoço/}));await userEvent.click(screen.getByRole('menuitem',{name:'Remover'}));expect(await screen.findByText('Almoço')).toBeInTheDocument();expect(screen.getByRole('alert')).toHaveTextContent('Não foi possível remover.')})

test('transferência usa rótulo e valor neutros sem depender de cor',async()=>{const transfer={...transaction,kind:'transfer' as const,description:'Transferência para Reserva',destinationAccountId:'b',destinationAccountName:'Reserva',categoryId:undefined,categoryName:undefined};render(<App api={mockAPI({...transactionData,dashboard:{...transactionData.dashboard,recentTransactions:[transfer]}})}/>);expect(await screen.findByText('Principal para Reserva')).toBeInTheDocument();const label=screen.getByText('Transferência:');expect(label.parentElement).toHaveClass('transfer');expect(label.parentElement?.textContent).not.toMatch(/[+−]/)})

test('oculta saldos da dashboard sem ocultar valores de movimentação',async()=>{const data:BootstrapData={...transactionData,profile:{...profile,balancesHidden:false},dashboard:{...transactionData.dashboard,totalBalanceCents:8710,pendingFixedExpensesCents:0,balanceHistory:[{month:'2026-02',label:'fev.',balanceCents:7000},{month:'2026-08',label:'ago.',balanceCents:8710}],accountAllocations:[{accountId:'a',accountName:'Principal',balanceCents:8710}]}};const api=mockAPI(data);render(<App api={api}/>);expect(await screen.findByText('Evolução do saldo')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Ocultar saldos'}));expect(api.SetBalancesHidden).toHaveBeenCalledWith(true);expect(screen.getAllByText('Saldos ocultos')).toHaveLength(2);expect(screen.getByText('Almoço')).toBeInTheDocument();expect(screen.getAllByText(/R\$\s*12,90/).length).toBeGreaterThan(0)})

test('cria despesa fixa pela navegação e confirma uma previsão com valor real',async()=>{const occurrence={id:'o',fixedExpenseId:'f',referenceMonth:'2026-08',dueDate:'2026-08-20',description:'Internet',expectedAmountCents:9990,accountId:'a',accountName:'Principal',categoryId:'bills',categoryName:'Contas',status:'pending' as const,createdAt:'x',updatedAt:'x'};const expense={id:'f',description:'Internet',amountCents:9990,dueDay:20,accountId:'a',accountName:'Principal',categoryId:'bills',categoryName:'Contas',createdAt:'x',updatedAt:'x'};const data:BootstrapData={...accountData,categories:[...empty.categories,{id:'bills',name:'Contas',kind:'expense'}]};const api=mockAPI(data);api.FixedExpensesOverview.mockResolvedValue({expenses:[expense],occurrences:[occurrence]});render(<App api={api}/>);await userEvent.click(await screen.findByRole('button',{name:'Despesas fixas'}));expect(await screen.findByText('O que falta pagar')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:/Confirmar/}));const value=screen.getByRole('textbox',{name:'Valor pago'});await userEvent.clear(value);await userEvent.type(value,'105,00');await userEvent.click(screen.getByRole('button',{name:'Confirmar pagamento'}));await waitFor(()=>expect(api.ConfirmFixedExpenseOccurrence).toHaveBeenCalledWith('o',expect.objectContaining({amountCents:10500})));await userEvent.click(screen.getByRole('button',{name:'Adicionar'}));await userEvent.type(screen.getByRole('textbox',{name:'Descrição'}),'Aluguel');await userEvent.type(screen.getByRole('textbox',{name:'Valor estimado'}),'1200,00');await userEvent.type(screen.getByRole('spinbutton',{name:'Dia do vencimento'}),'10');const category=screen.getByRole('combobox',{name:'Categoria'});await userEvent.type(category,'contas');await userEvent.keyboard('{Home}{Enter}');await userEvent.click(screen.getByRole('button',{name:'Criar despesa fixa'}));await waitFor(()=>expect(api.CreateFixedExpense).toHaveBeenCalledWith(expect.objectContaining({description:'Aluguel',amountCents:120000,dueDay:10,accountId:'a',categoryId:'bills'})))})
