import { useRef, useState } from 'react'
import { AccountActions, Button, EmptyState, Icon, Sheet } from '../components'
import { AccountForm, BalanceAdjustmentDialog, DeleteAccountDialog } from '../forms'
import { formatBRL, formatDate, parseBRL, today } from '../format'
import { formatMonth } from './dashboard'
import type { Account, AccountInput, BalanceAdjustmentInput, BootstrapData, CreditCardInvoice, CreditCardPaymentInput, CreditCardsOverview } from '../types'

const errorMessage = (error: unknown) => error instanceof Error ? error.message : String(error)

export function AccountsView({ data, create, update, adjust, remove }: { data: BootstrapData; create(input: AccountInput): Promise<void>; update(id: string, input: AccountInput): Promise<void>; adjust(id: string, input: BalanceAdjustmentInput): Promise<void>; remove(id: string): Promise<void> }) {
  const [creating, setCreating] = useState(data.accounts.length === 0), [editing, setEditing] = useState<Account | undefined>(), [adjusting, setAdjusting] = useState<Account | undefined>(), [deleting, setDeleting] = useState<Account | undefined>()
  const actionTrigger = useRef<HTMLElement | null>(null), addTrigger = useRef<HTMLButtonElement>(null)
  const closeEditor = () => { setCreating(false); setEditing(undefined); requestAnimationFrame(() => actionTrigger.current?.focus()) }
  const closeDelete = () => { setDeleting(undefined); requestAnimationFrame(() => actionTrigger.current?.focus()) }
  return <div className="page page--split"><section><div className="section-heading"><p className="section-summary">{data.accounts.length ? `${data.accounts.length} ${data.accounts.length === 1 ? 'conta cadastrada' : 'contas cadastradas'}` : 'Nenhuma conta cadastrada'}</p>{!creating && !editing && <Button ref={addTrigger} kind="secondary" onClick={() => { setCreating(true); setEditing(undefined) }}><Icon name="plus"/> Adicionar</Button>}</div>{data.accounts.length ? <div className="account-grid">{data.accounts.map(account => <article className="account-card" key={account.id}><AccountActions account={account} onEdit={(item, trigger) => { actionTrigger.current = trigger; setCreating(false); setEditing(item) }} onAdjust={(item, trigger) => { actionTrigger.current=trigger; setAdjusting(item) }} onRemove={(item, trigger) => { actionTrigger.current = trigger; setDeleting(item) }}/><span>{account.type === 'checking' ? 'Conta corrente' : account.type === 'savings' ? 'Poupança' : account.type==='credit_card'?'Cartão de crédito':'Dinheiro'}</span><h3>{account.name}</h3><strong>{formatBRL(account.type==='credit_card'?Math.max(0,-account.currentBalanceCents):account.currentBalanceCents)}</strong><small>{account.type==='credit_card'?`Em aberto · limite ${formatBRL(account.creditLimitCents??0)}`:'Saldo calculado'}</small></article>)}</div> : !creating && <EmptyState icon="walletMinimal" title="Nenhuma conta ainda" action={<Button onClick={() => setCreating(true)}>Criar conta</Button>}>Crie sua primeira conta para registrar movimentações.</EmptyState>}</section>{(creating || editing) && <AccountForm key={editing?.id ?? 'new'} initial={editing} onSubmit={async input => { if (editing) await update(editing.id, input); else await create(input); closeEditor() }} onCancel={closeEditor}/>} {adjusting&&<BalanceAdjustmentDialog account={adjusting} onClose={()=>{setAdjusting(undefined);requestAnimationFrame(()=>actionTrigger.current?.focus())}} onSubmit={input=>adjust(adjusting.id,input)}/>} {deleting && <DeleteAccountDialog account={deleting} onClose={closeDelete} onConfirm={async () => { await remove(deleting.id); setDeleting(undefined); requestAnimationFrame(() => addTrigger.current?.focus()) }}/>}</div>
}

export function CreditCardsView({data,overview,onPay,onCreateCard}:{data:BootstrapData;overview:CreditCardsOverview|null;onPay(id:string,input:CreditCardPaymentInput):Promise<void>;onCreateCard():void}){
  const [paying,setPaying]=useState<CreditCardInvoice|undefined>(),[accountId,setAccountId]=useState(''),[amount,setAmount]=useState(''),[paymentError,setPaymentError]=useState(''),[busy,setBusy]=useState(false)
  const sources=data.accounts.filter(account=>account.type!=='credit_card')
  if(!overview)return <div className="page"><section className="card"><p className="analysis-empty">Carregando cartões e faturas…</p></section></div>
  if(!overview.cards.length)return <div className="page"><EmptyState icon="wallet" title="Nenhum cartão cadastrado" action={<Button onClick={onCreateCard}>Adicionar cartão</Button>}>Cadastre limite, fechamento e vencimento para organizar compras e faturas.</EmptyState></div>
  const openPayment=(invoice:CreditCardInvoice)=>{setPaying(invoice);setAccountId(sources[0]?.id??'');setAmount((invoice.outstandingCents/100).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}));setPaymentError('')}
  const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!paying)return;const cents=parseBRL(amount);if(cents===null||cents<=0)return setPaymentError('Informe um valor maior que zero.');setBusy(true);setPaymentError('');try{await onPay(paying.id,{accountId,amountCents:cents,occurrenceDate:today()});setPaying(undefined)}catch(err){setPaymentError(errorMessage(err))}finally{setBusy(false)}}
  const status=(value:CreditCardInvoice['status'])=>value==='open'?'Aberta':value==='closed'?'Fechada':value==='paid'?'Paga':'Transferida'
  return <div className="page cards-page"><section className="card-summary-grid">{overview.cards.map(card=><article className={`card credit-summary ${card.availableLimitCents<0?'negative':''}`} key={card.account.id}><span>Cartão de crédito</span><h2>{card.account.name}</h2><p>Em aberto <strong>{formatBRL(card.outstandingCents)}</strong></p><small>Limite disponível {formatBRL(card.availableLimitCents)} · fecha dia {card.account.closingDay} · vence dia {card.account.dueDay}</small></article>)}</section><section className="card invoice-list"><div className="card__heading"><div><h2>Faturas</h2><p>Compras parceladas aparecem no mês em que serão cobradas.</p></div></div>{overview.invoices.length?<ul>{overview.invoices.map(invoice=><li key={invoice.id}><div><span className="occurrence-status">{status(invoice.status)}</span><strong>{invoice.accountName} · {formatMonth(invoice.referenceMonth)}</strong><small>Fecha {formatDate(invoice.closingDate)} · vence {formatDate(invoice.dueDate)}</small>{invoice.installments.length>0&&<span>{invoice.installments.map(item=><small key={item.id}>{item.description}{item.installmentCount>1?` · ${item.installmentNumber}/${item.installmentCount}`:''} · {formatBRL(item.amountCents)}</small>)}</span>}</div><div><strong>{formatBRL(invoice.outstandingCents)}</strong>{(invoice.status==='open'||invoice.status==='closed')&&invoice.outstandingCents>0&&<Button kind="secondary" disabled={!sources.length} onClick={()=>openPayment(invoice)}>Pagar fatura</Button>}</div></li>)}</ul>:<p className="analysis-empty">As faturas aparecerão depois da primeira compra.</p>}</section>{paying&&<Sheet onClose={()=>setPaying(undefined)} busy={busy} labelledBy="pay-invoice-title" className="dialog--confirm"><header><h2 id="pay-invoice-title">Pagar fatura de {formatMonth(paying.referenceMonth)}</h2><button className="icon-button" type="button" disabled={busy} onClick={()=>setPaying(undefined)} aria-label="Fechar"><Icon name="close"/></button></header><form onSubmit={submit} aria-busy={busy||undefined}><label className="field"><span>Conta de pagamento</span><select autoFocus value={accountId} onChange={event=>setAccountId(event.target.value)} required>{sources.map(account=><option value={account.id} key={account.id}>{account.name}</option>)}</select></label><label className="field"><span>Valor do pagamento</span><div className="money-input"><span>R$</span><input value={amount} onChange={event=>setAmount(event.target.value)} inputMode="decimal" required/></div></label>{paymentError&&<p className="form-error" role="alert">{paymentError}</p>}<div className="form-actions"><Button kind="ghost" type="button" disabled={busy} onClick={()=>setPaying(undefined)}>Cancelar</Button><Button loading={busy} state={paymentError?'error':'idle'}>Confirmar pagamento</Button></div></form></Sheet>}</div>
}
