import { Button, EmptyState, Icon, TransactionList } from '../components'
import { formatBRL, formatDate } from '../format'
import type { BootstrapData, Transaction } from '../types'

export function DashboardView({ data, balancesHidden, onBalancesHiddenChange, onAccounts, onTransactions, onTransaction, onEdit, onRemove }: { data: BootstrapData; balancesHidden: boolean; onBalancesHiddenChange(hidden: boolean): void; onAccounts(): void; onTransactions(): void; onTransaction(): void; onEdit(tx: Transaction, trigger: HTMLElement): void; onRemove(tx: Transaction, trigger: HTMLElement): void }) {
  const d = data.dashboard, total = d.totalBalanceCents ?? d.availableBalanceCents, pending = d.pendingFixedExpensesCents ?? 0, pendingCount = d.pendingFixedExpenseCount ?? 0
  return <div className="page dashboard-page"><section className={`balance-hero ${d.hasNegativeBalance ? 'negative' : ''}`} aria-labelledby="available-balance-label"><div className="balance-hero__content"><p className="balance-hero__label" id="available-balance-label"><span>Disponível após despesas fixas</span><button className="balance-visibility" type="button" aria-label={balancesHidden ? 'Mostrar saldos' : 'Ocultar saldos'} aria-pressed={balancesHidden} title={balancesHidden ? 'Mostrar saldos' : 'Ocultar saldos'} onClick={() => onBalancesHiddenChange(!balancesHidden)}><Icon name={balancesHidden ? 'eyeOff' : 'eye'}/></button></p><strong className="balance-hero__value" aria-label={balancesHidden ? 'Saldo oculto' : undefined}>{balancesHidden ? '••••••' : formatBRL(d.availableBalanceCents)}</strong></div><div className="balance-hero__meta" aria-label="Contexto do saldo disponível"><div className="balance-hero__meta-row"><span>{pendingCount ? `${pendingCount} compromisso${pendingCount === 1 ? '' : 's'} pendente${pendingCount === 1 ? '' : 's'}` : 'Compromissos pendentes'}</span><strong>{balancesHidden ? 'Oculto' : pendingCount ? formatBRL(pending) : 'Nenhum'}</strong></div><div className="balance-hero__meta-row"><span>Saldo total</span><strong>{balancesHidden ? 'Oculto' : formatBRL(total)}</strong></div></div></section>
    {d.hasNegativeBalance && <div className="warning" role="status"><Icon name="warning"/><span><strong>Seu saldo está negativo.</strong> Revise os registros e evite novos compromissos até regularizar.</span></div>}
    <section className="dashboard-ledger" aria-labelledby="dashboard-ledger-title"><header className="dashboard-ledger__header"><p>Leitura rápida</p><h2 id="dashboard-ledger-title">Fluxo e planejamento</h2></header><div className="dashboard-ledger__columns"><section className="dashboard-ledger__column dashboard-ledger__column--monthly metrics" aria-labelledby="dashboard-monthly-title"><h3 id="dashboard-monthly-title">Movimentação</h3><article className="dashboard-ledger__row dashboard-ledger__row--income"><div><p>Receitas no mês</p><small>Entradas registradas</small></div><strong>+ {formatBRL(d.monthlyIncomeCents)}</strong></article><article className="dashboard-ledger__row dashboard-ledger__row--expense"><div><p>Despesas no mês</p><small>Saídas registradas</small></div><strong>− {formatBRL(d.monthlyExpenseCents)}</strong></article><article className="dashboard-ledger__row dashboard-ledger__row--result"><div><p>Resultado do mês</p><small>Receitas menos despesas</small></div><strong>{formatBRL(d.monthlyIncomeCents - d.monthlyExpenseCents)}</strong></article></section><section className="dashboard-ledger__column dashboard-ledger__column--planning planning-strip" aria-labelledby="dashboard-planning-title"><h3 id="dashboard-planning-title">Planejamento</h3><article className="dashboard-ledger__row"><div><p>Valor reservado</p><small>Separado para objetivos</small></div><strong>{balancesHidden?'••••••':formatBRL(d.reservedValueCents??0)}</strong></article><article className="dashboard-ledger__row"><div><p>Valor livre</p><small>Disponível para novas escolhas</small></div><strong>{balancesHidden?'••••••':formatBRL(d.freeValueCents??d.availableBalanceCents)}</strong></article><article className="dashboard-ledger__row dashboard-ledger__row--goal"><div><p>Progresso das metas</p><small>Objetivos ativos</small></div><strong>{Math.round(d.goalProgressPercent??0)}%</strong></article></section></div></section>
    {(d.creditCardDebtCents??0)>0&&<section className="card invoice-dashboard"><div><h2>Cartões de crédito</h2><p>Dívida reconhecida no patrimônio</p></div><strong>{balancesHidden?'••••••':formatBRL(d.creditCardDebtCents??0)}</strong>{d.upcomingInvoices?.[0]&&<small>Próxima fatura vence {formatDate(d.upcomingInvoices[0].dueDate)} · {balancesHidden?'valor oculto':formatBRL(d.upcomingInvoices[0].outstandingCents)}</small>}</section>}
    <section className="dashboard-analysis" aria-label="Evolução e distribuição dos saldos"><BalanceTrendChart points={d.balanceHistory ?? []} hidden={balancesHidden}/><AccountAllocationChart allocations={d.accountAllocations ?? []} hidden={balancesHidden}/></section>
    <section className="card"><div className="card__heading"><div><h2>Atividade recente</h2></div>{d.recentTransactions.length > 0 && <button className="text-button" onClick={onTransactions}>Ver todas <Icon name="chevronRight"/></button>}</div><TransactionList transactions={d.recentTransactions} onEdit={onEdit} onRemove={onRemove} empty={<EmptyState icon={data.accounts.length ? 'receipt' : 'walletMinimal'} title={data.accounts.length ? 'Seu histórico começa aqui' : 'Crie sua primeira conta'} action={<Button onClick={data.accounts.length ? onTransaction : onAccounts}>{data.accounts.length ? 'Registrar movimentação' : 'Criar conta'}</Button>}>{data.accounts.length ? 'Registre uma receita, despesa ou transferência para acompanhar seu mês.' : 'Adicione onde você guarda dinheiro para começar a organizar.'}</EmptyState>}/></section></div>
}

function BalanceTrendChart({ points, hidden }: { points: NonNullable<BootstrapData['dashboard']['balanceHistory']>; hidden: boolean }) {
  if (hidden) return <section className="card analysis-card analysis-card--hidden" aria-label="Evolução do saldo"><div><h2>Evolução do saldo</h2></div><p role="status">Saldos ocultos</p></section>
  if (!points.length) return <section className="card analysis-card"><div><h2>Evolução do saldo</h2></div><p className="analysis-empty">Registre movimentações para acompanhar sua evolução.</p></section>
  const values = points.map(point => point.balanceCents), min = Math.min(...values), max = Math.max(...values), range = Math.max(max - min, 1)
  const positions = points.map((point, index) => ({ ...point, x: 24 + (512 * index) / Math.max(points.length - 1, 1), y: 24 + (112 * (max - point.balanceCents)) / range }))
  const path = positions.map((point, index) => `${index ? 'L' : 'M'}${point.x.toFixed(1)},${point.y.toFixed(1)}`).join(' ')
  return <section className="card analysis-card"><div className="card__heading"><div><h2>Evolução do saldo</h2></div><span className="analysis-total">{formatBRL(points.at(-1)?.balanceCents ?? 0)}</span></div><figure className="trend-chart"><svg viewBox="0 0 560 180" role="img" aria-labelledby="trend-title trend-description"><title id="trend-title">Evolução do saldo total nos últimos sete meses</title><desc id="trend-description">O saldo mais recente é {formatBRL(points.at(-1)?.balanceCents ?? 0)}.</desc><path className="trend-chart__baseline" d="M24 140H536"/><path className="trend-chart__line" pathLength="1" d={path}/>{positions.map(point => <circle key={point.month} className="trend-chart__point" cx={point.x} cy={point.y} r="4"><title>{formatMonth(point.month)}: {formatBRL(point.balanceCents)}</title></circle>)}</svg><figcaption>{points.map(point => <span key={point.month}>{formatMonth(point.month)}</span>)}</figcaption></figure><ul className="sr-only">{points.map(point => <li key={point.month}>{formatMonth(point.month)}: {formatBRL(point.balanceCents)}</li>)}</ul></section>
}

function AccountAllocationChart({ allocations, hidden }: { allocations: NonNullable<BootstrapData['dashboard']['accountAllocations']>; hidden: boolean }) {
  if (hidden) return <section className="card allocation-card analysis-card--hidden" aria-label="Saldos por conta"><div><h2>Onde está seu dinheiro</h2></div><p role="status">Saldos ocultos</p></section>
  if (!allocations.length) return <section className="card allocation-card"><div><h2>Onde está seu dinheiro</h2></div><p className="analysis-empty">Suas contas aparecerão aqui.</p></section>
  const largest = Math.max(...allocations.map(item => Math.abs(item.balanceCents)), 1)
  return <section className="card allocation-card"><div><h2>Onde está seu dinheiro</h2></div><ul className="allocation-list">{allocations.map(item => <li key={item.accountId}><div><span>{item.accountName}</span><strong>{formatBRL(item.balanceCents)}</strong></div><span className={`allocation-bar ${item.balanceCents < 0 ? 'negative' : ''}`} aria-hidden="true"><i style={{ width: `${Math.max((Math.abs(item.balanceCents) / largest) * 100, 3)}%` }}/></span></li>)}</ul></section>
}

export function formatMonth(month: string) { return ['jan.', 'fev.', 'mar.', 'abr.', 'mai.', 'jun.', 'jul.', 'ago.', 'set.', 'out.', 'nov.', 'dez.'][Number(month.slice(5, 7)) - 1] ?? month }
