import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import type { api as defaultAPI } from '../api'
import { Button, Icon, Modal } from '../components'
import type { BackupInfo, BackupStatus, SecurityStatus, Theme, UpdateStatus } from '../types'

type API = typeof defaultAPI

const errorMessage = (error: unknown) => error instanceof Error ? error.message : String(error)

export function UnlockScreen({ api, onUnlocked }: { api: API; onUnlocked(status: SecurityStatus): Promise<void> }) {
  const [recovery, setRecovery] = useState(false), [password, setPassword] = useState(''), [recoveryKey, setRecoveryKey] = useState(''), [newPassword, setNewPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError('')
    try {
      if (recovery) {
        if (!api.RecoverEncryption) throw new Error('Recuperação indisponível nesta instalação.')
        await onUnlocked(await api.RecoverEncryption({ recoveryKey, newPassword, confirmation }))
      } else {
        if (!api.UnlockDatabase) throw new Error('Desbloqueio indisponível nesta instalação.')
        await onUnlocked(await api.UnlockDatabase({ password }))
      }
    } catch (err) { setError(errorMessage(err)); setBusy(false) }
  }
  return <main className="unlock-screen"><section className="unlock-card" aria-labelledby="unlock-title"><div className="brand"><span>[c]</span>ash</div><p className="context-label">Dados protegidos</p><h1 id="unlock-title">Desbloqueie seu banco de dados</h1><p>{recovery ? 'Use a chave guardada por você para definir uma nova senha.' : 'A senha é solicitada em toda abertura. Ela nunca é armazenada.'}</p><form onSubmit={submit}>{recovery ? <><label className="field"><span>Chave de recuperação</span><textarea autoFocus value={recoveryKey} onChange={event => setRecoveryKey(event.target.value)} autoComplete="off" required/></label><label className="field"><span>Nova senha</span><input type="password" value={newPassword} onChange={event => setNewPassword(event.target.value)} minLength={12} autoComplete="new-password" required/></label><label className="field"><span>Confirme a nova senha</span><input type="password" value={confirmation} onChange={event => setConfirmation(event.target.value)} minLength={12} autoComplete="new-password" required/></label></> : <label className="field"><span>Senha</span><input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)} autoComplete="current-password" required/></label>}{error && <p className="form-error" role="alert">{error}</p>}<Button loading={busy}>{recovery ? 'Redefinir senha e entrar' : 'Desbloquear'}</Button></form><button type="button" className="text-button" disabled={busy} onClick={() => { setRecovery(value => !value); setError('') }}>{recovery ? 'Voltar para a senha' : 'Esqueci minha senha'}</button></section></main>
}

export function SettingsView({ api, theme, security, updateStatus, setTheme, onCheckUpdates, onShowUpdate, onRestored, onSecurityChange }: { api: API; theme: Theme; security: SecurityStatus; updateStatus: UpdateStatus | null; setTheme(value: Theme): Promise<void>; onCheckUpdates(): Promise<void>; onShowUpdate(): void; onRestored(): Promise<void>; onSecurityChange(status: SecurityStatus): void }) {
  const checking = updateStatus?.state === 'checking'
  const label = updateStatus?.state === 'disabled' ? 'Atualizações indisponíveis neste build' : updateStatus?.state === 'available' ? `Versão ${updateStatus.availableVersion} disponível` : updateStatus?.state === 'downloading' ? 'Baixando atualização…' : updateStatus?.state === 'installing' ? 'Preparando instalação…' : updateStatus?.state === 'upToDate' ? 'Você já está usando a versão mais recente' : updateStatus?.message || `Versão ${updateStatus?.currentVersion || 'dev'}`
  const [backup, setBackup] = useState<BackupStatus | null>(null), [message, setMessage] = useState(''), [operationError, setOperationError] = useState(''), [busy, setBusy] = useState(''), [securityMode, setSecurityMode] = useState<'enable'|'change'|'recover'|'disable'|null>(null), [password, setPassword] = useState(''), [currentPassword, setCurrentPassword] = useState(''), [confirmation, setConfirmation] = useState(''), [recoveryKey, setRecoveryKey] = useState(''), [archiveRecoveryKey, setArchiveRecoveryKey] = useState(''), [savedRecovery, setSavedRecovery] = useState(false), [restore, setRestore] = useState<BackupInfo | null>(null)
  const settingsDialogTrigger = useRef<HTMLButtonElement | null>(null)
  const refreshBackup = useCallback(async () => { if (api.BackupStatus) setBackup(await api.BackupStatus()) }, [api])
  useEffect(() => { void refreshBackup().catch(err => setOperationError(errorMessage(err))) }, [refreshBackup])
  const run = async (name: string, action: () => Promise<void>) => { setBusy(name); setMessage(''); setOperationError(''); try { await action() } catch (err) { setOperationError(errorMessage(err)) } finally { setBusy('') } }
  const clearSecurityDialog = () => { setSecurityMode(null); setPassword(''); setCurrentPassword(''); setConfirmation(''); if (!savedRecovery) setRecoveryKey(''); requestAnimationFrame(() => settingsDialogTrigger.current?.focus()) }
  const openSecurity = (mode: NonNullable<typeof securityMode>, trigger: HTMLButtonElement) => { settingsDialogTrigger.current = trigger; setSecurityMode(mode) }
  const submitSecurity = async (event: FormEvent) => { event.preventDefault(); await run('security', async () => {
    if (securityMode === 'enable') { if (!api.EnableEncryption) return; const result = await api.EnableEncryption({ password, confirmation }); onSecurityChange(result.status); setRecoveryKey(result.recoveryKey ?? ''); setSavedRecovery(false); setMessage('Criptografia ativada.') }
    if (securityMode === 'change') { await api.ChangeEncryptionPassword?.({ currentPassword, newPassword: password, confirmation }); setMessage('Senha alterada.') ; clearSecurityDialog() }
    if (securityMode === 'recover') { if (!api.RecoverEncryption) return; onSecurityChange(await api.RecoverEncryption({ recoveryKey, newPassword: password, confirmation })); setMessage('Senha redefinida com a chave de recuperação.'); setSavedRecovery(true); clearSecurityDialog() }
    if (securityMode === 'disable') { if (!api.DisableEncryption) return; onSecurityChange(await api.DisableEncryption({ password })); setMessage('Criptografia desativada. O banco voltou a ser armazenado sem proteção.'); clearSecurityDialog() }
  }) }
  const inspect = (trigger: HTMLButtonElement) => { settingsDialogTrigger.current = trigger; return run('restore', async () => { const result = await api.InspectBackup?.(); if (result && !result.cancelled) setRestore(result.backup) }) }
  const restoreNow = () => restore && run('restore-confirm', async () => {
    const result = await api.RestoreBackup?.({ path: restore.path, password, recoveryKey: archiveRecoveryKey })
    if (!result?.success) return
    setRestore(null)
    setPassword('')
    setArchiveRecoveryKey('')
    setMessage('Backup restaurado com sucesso.')
    if (api.SecurityStatus) onSecurityChange(await api.SecurityStatus())
    await refreshBackup()
    await onRestored()
  })
  return <div className="page settings-page">
    {operationError && !securityMode && !restore && <p className="alert" role="alert">{operationError}</p>}{message && <p className="alert alert--success" role="status">{message}</p>}
    <nav className="settings-index" aria-label="Seções de configurações"><a href="#settings-appearance"><Icon name="palette"/>Aparência</a><a href="#settings-data"><Icon name="walletMinimal"/>Dados e backup</a><a href="#settings-security"><Icon name="shieldCheck"/>Segurança</a><a href="#settings-updates"><Icon name="restore"/>Atualizações</a><a href="#settings-about"><Icon name="receipt"/>Sobre</a></nav>
    <section id="settings-appearance" className="card settings-card settings-section"><h2>Tema do aplicativo</h2><p>Escolha como o [c]ash aparece. A estrutura e os dados permanecem os mesmos em qualquer tema.</p><fieldset className="settings-themes"><legend className="sr-only">Tema</legend>{(['light', 'dark', 'gothic'] as Theme[]).map(value => <label key={value}><input type="radio" name="settings-theme" value={value} checked={theme === value} onChange={() => void setTheme(value)}/><span className={`settings-swatch settings-swatch--${value}`} aria-hidden="true"><i/><i/></span><strong>{value === 'light' ? 'Claro' : value === 'dark' ? 'Escuro' : 'Gótico'}</strong><small>{value === 'light' ? 'Calmo e luminoso' : value === 'dark' ? 'Confortável à noite' : 'Carvão e vinho'}</small></label>)}</fieldset></section>
    <section id="settings-data" className="card portability-card settings-section"><div className="settings-section-heading"><div><h2>Backup e portabilidade</h2><p>Crie uma cópia local, escolha onde guardá-la ou restaure uma versão anterior.</p></div><span className={`status-pill ${backup?.lastError ? 'status-pill--error' : ''}`}>{backup?.lastError ? 'Atenção necessária' : 'Automático'}</span></div><dl className="settings-details"><div><dt>Pasta</dt><dd title={backup?.folder}>{backup?.folder ?? 'Carregando…'}</dd></div><div><dt>Último automático</dt><dd>{backup?.lastAutomaticAt ? formatDateTime(backup.lastAutomaticAt) : 'Ainda não realizado'}</dd></div><div><dt>Próximo</dt><dd>{backup?.automaticDue ? 'Será criado na próxima abertura' : backup?.nextDueAt ? formatDateTime(backup.nextDueAt) : 'Após sete dias'}</dd></div></dl>{backup?.lastError && <p className="form-error" role="status">Última falha: {backup.lastError}</p>}<div className="settings-actions"><Button loading={busy === 'backup'} onClick={() => void run('backup', async () => { const result = await api.CreateBackup?.(); if (result && !result.cancelled) setMessage('Backup salvo com sucesso.'); await refreshBackup() })}>Criar backup agora</Button><Button kind="secondary" loading={busy === 'restore'} onClick={event => void inspect(event.currentTarget)}>Restaurar backup</Button><Button kind="ghost" onClick={() => void run('folder', async () => { const result = await api.ChooseBackupFolder?.(); if (result && !result.cancelled) await refreshBackup() })}>Escolher pasta</Button>{backup && backup.folder !== backup.defaultFolder && <button className="text-button" onClick={() => void run('folder', async () => { if (api.ResetBackupFolder) setBackup(await api.ResetBackupFolder()) })}>Usar pasta padrão</button>}</div><div className="export-panel"><div><strong>Exportar relatórios</strong><p>CSV e JSON são arquivos em texto puro, mesmo quando a criptografia está ativada. Guarde-os em local seguro; eles não podem ser usados para restauração.</p></div><div><Button kind="secondary" loading={busy === 'csv'} onClick={() => void run('csv', async () => { const result = await api.ExportData?.('csv'); if (result && !result.cancelled) setMessage('CSV exportado com sucesso.') })}>Exportar CSV</Button><Button kind="secondary" loading={busy === 'json'} onClick={() => void run('json', async () => { const result = await api.ExportData?.('json'); if (result && !result.cancelled) setMessage('JSON exportado com sucesso.') })}>Exportar JSON</Button></div></div></section>
    <section id="settings-security" className="card security-card settings-section"><div className="settings-section-heading"><div><h2>Criptografia</h2><p>{security.enabled ? 'O banco completo está protegido. A senha será exigida em toda abertura.' : 'Ative uma senha para proteger o arquivo local do banco.'}</p></div><span className={`status-pill ${security.enabled ? 'status-pill--secure' : ''}`}>{security.enabled ? 'Ativada' : 'Desativada'}</span></div><div className="settings-actions">{security.enabled ? <><Button kind="secondary" onClick={event => openSecurity('change', event.currentTarget)}>Alterar senha</Button><Button kind="secondary" onClick={event => openSecurity('recover', event.currentTarget)}>Redefinir com chave de recuperação</Button><Button kind="ghost" onClick={event => openSecurity('disable', event.currentTarget)}>Desativar criptografia</Button></> : <Button onClick={event => openSecurity('enable', event.currentTarget)}>Ativar criptografia</Button>}</div></section>
    <section id="settings-updates" className="card update-card settings-section"><div><h2>Atualizações e versão</h2><p>{label}</p>{updateStatus?.lastCheckedAt && <small>Última verificação: {formatDateTime(updateStatus.lastCheckedAt)}</small>}</div><div className="update-card__actions">{updateStatus?.state === 'available' && <Button onClick={onShowUpdate}>Atualizar agora</Button>}<Button kind="secondary" loading={checking} onClick={() => void onCheckUpdates()} disabled={updateStatus?.state === 'disabled'}>{checking ? 'Verificando…' : 'Verificar agora'}</Button></div></section>
    <section id="settings-about" className="card licenses-card settings-section"><h2>Software aberto, dados privados</h2><details><summary>Licenças de código aberto</summary><h3>SQLCipher — BSD 3-Clause</h3><pre>{`Copyright (c) 2025, ZETETIC LLC
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
* Neither the name of the ZETETIC LLC nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY ZETETIC LLC ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ZETETIC LLC BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`}</pre></details></section>
    {securityMode && !(securityMode === 'enable' && recoveryKey) && <Modal onClose={clearSecurityDialog} busy={busy === 'security'} labelledBy="security-dialog-title" className="security-dialog" alert={securityMode === 'disable'}><header><div><p className="context-label">{securityMode === 'enable' ? 'Proteção do banco' : securityMode === 'change' ? 'Nova credencial' : securityMode === 'recover' ? 'Recuperação local' : 'Ação destrutiva'}</p><h2 id="security-dialog-title">{securityMode === 'enable' ? 'Ativar criptografia' : securityMode === 'change' ? 'Alterar senha' : securityMode === 'recover' ? 'Redefinir senha' : 'Desativar criptografia?'}</h2></div><button type="button" className="icon-button" aria-label="Fechar" disabled={busy === 'security'} onClick={clearSecurityDialog}><Icon name="close"/></button></header><p>{securityMode === 'disable' ? 'O banco será convertido para texto não criptografado. Um backup de segurança protegido será criado antes.' : 'Use pelo menos 12 caracteres. Não existe recuperação remota nem chave mestra.'}</p>{operationError && <p className="form-error" role="alert">{operationError}</p>}<form onSubmit={submitSecurity} aria-busy={busy === 'security'||undefined}>{securityMode === 'change' && <label className="field"><span>Senha atual</span><input autoFocus type="password" value={currentPassword} onChange={event => setCurrentPassword(event.target.value)} required/></label>}{securityMode === 'recover' && <label className="field"><span>Chave de recuperação</span><textarea autoFocus value={recoveryKey} onChange={event => setRecoveryKey(event.target.value)} required/></label>}<label className="field"><span>{securityMode === 'disable' ? 'Senha atual' : 'Nova senha'}</span><input autoFocus={securityMode !== 'change' && securityMode !== 'recover'} type="password" value={password} onChange={event => setPassword(event.target.value)} minLength={securityMode === 'disable' ? undefined : 12} required/></label>{securityMode !== 'disable' && <label className="field"><span>Confirme a senha</span><input type="password" value={confirmation} onChange={event => setConfirmation(event.target.value)} minLength={12} required/></label>}<div className="form-actions"><Button type="button" kind="ghost" disabled={busy === 'security'} onClick={clearSecurityDialog}>Cancelar</Button><Button loading={busy === 'security'} state={operationError?'error':'idle'}>{securityMode === 'disable' ? 'Desativar e converter' : securityMode === 'change' ? 'Alterar senha' : securityMode === 'recover' ? 'Redefinir senha' : 'Criptografar banco'}</Button></div></form></Modal>}
    {securityMode === 'enable' && recoveryKey && <Modal onClose={()=>undefined} dismissible={false} labelledBy="recovery-title" className="recovery-dialog"><p className="context-label">Exibida uma única vez</p><h2 id="recovery-title">Guarde sua chave de recuperação</h2><p>Ela permite redefinir a senha. O [c]ash não guarda uma cópia e não poderá recuperá-la para você.</p><output className="recovery-key">{recoveryKey}</output><label className="confirmation-check"><input type="checkbox" checked={savedRecovery} onChange={event => setSavedRecovery(event.target.checked)}/><span>Salvei a chave em um local seguro</span></label><Button disabled={!savedRecovery} onClick={() => { setRecoveryKey(''); clearSecurityDialog() }}>Concluir</Button></Modal>}
    {restore && <Modal onClose={() => { setRestore(null); setPassword(''); setArchiveRecoveryKey('') }} busy={busy === 'restore-confirm'} labelledBy="restore-title" className="restore-dialog" alert><p className="context-label">Substituição de dados</p><h2 id="restore-title">Restaurar este backup?</h2><p>Os dados atuais serão substituídos pelos dados de {formatDateTime(restore.manifest.createdAt)}. Antes disso, criaremos um backup de segurança que nunca é apagado automaticamente.</p><dl className="settings-details"><div><dt>Versão do formato</dt><dd>{restore.manifest.formatVersion}</dd></div><div><dt>Criptografia</dt><dd>{restore.manifest.encrypted ? 'Protegido' : 'Sem criptografia'}</dd></div></dl>{restore.manifest.encrypted && <><label className="field"><span>Senha do backup, se diferente da atual</span><input autoFocus type="password" value={password} onChange={event => setPassword(event.target.value)}/></label><label className="field"><span>Ou chave de recuperação</span><textarea value={archiveRecoveryKey} onChange={event => setArchiveRecoveryKey(event.target.value)}/></label></>}{operationError && <p className="form-error" role="alert">{operationError}</p>}<div className="form-actions"><Button type="button" kind="ghost" disabled={busy === 'restore-confirm'} onClick={() => { setRestore(null); setPassword(''); setArchiveRecoveryKey('') }}>Cancelar</Button><Button loading={busy === 'restore-confirm'} state={operationError?'error':'idle'} onClick={() => void restoreNow()}>Restaurar e substituir</Button></div></Modal>}
  </div>
}

export function UpdateDialog({ status, onClose, onInstall }: { status: UpdateStatus; onClose(): void; onInstall(): Promise<void> }) {
  const [installing, setInstalling] = useState(false)
  const busy = installing || status.state === 'downloading' || status.state === 'installing'
  const progress = status.totalBytes ? Math.min(100, Math.round(((status.downloadedBytes ?? 0) / status.totalBytes) * 100)) : 0
  const install = async () => { setInstalling(true); try { await onInstall() } catch { setInstalling(false) } }
  const title = status.state === 'error' ? 'Não foi possível atualizar' : `Atualizar para ${status.availableVersion}`
  return <Modal onClose={onClose} busy={busy} labelledBy="update-title" className="update-dialog"><div className="dialog__heading"><div><p className="context-label">{status.state === 'error' ? 'Atualização interrompida' : 'Nova versão'}</p><h2 id="update-title">{title}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy} aria-label="Fechar"><Icon name="close"/></button></div>{status.state === 'downloading' ? <div className="update-dialog__progress" role="status"><span>Baixando atualização… {progress}%</span><progress value={status.downloadedBytes ?? 0} max={status.totalBytes ?? 1} aria-label={`Download da atualização: ${progress}%`}/></div> : status.state === 'installing' ? <p role="status">Encerrando o aplicativo para instalar a atualização…</p> : status.state === 'error' ? <p role="alert">{status.message || 'A versão anterior foi mantida. Tente novamente mais tarde.'}</p> : <><p>O aplicativo será fechado e reaberto quando a instalação terminar.</p>{status.releaseNotes && <pre className="update-dialog__notes">{status.releaseNotes}</pre>}</>}<div className="dialog__actions"><Button kind="secondary" onClick={onClose} disabled={busy}>{status.state === 'error' ? 'Fechar' : 'Depois'}</Button>{!busy && <Button loading={installing} state={status.state==='error'?'error':'idle'} onClick={() => void install()}>{status.state === 'error' ? 'Tentar novamente' : 'Baixar e instalar'}</Button>}</div></Modal>
}

function formatDateTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(date) }
